(()=>{'use strict';
const TILESET=window.CC_TILESET_INFO={name:"Chip's Challenge CC1 112-tile atlas",file:'tiles.png',tileSize:32,atlasWidth:416,atlasHeight:512,columns:13,rows:16,tileCount:112};
const MONSTER_DEFAULTS=window.CC_MONSTER_CONFIG=Object.assign({spiderMoveMs:800,spiralMoveMs:600,teethMoveMs:400,genericMonsterMoveMs:500,teethFocusMs:5000,defaultVisionTiles:10,focusLoseDistanceTiles:10},window.CC_MONSTER_CONFIG||{});
const LS='chips-editor-slot-';
const E={slot:0,tool:'paint',actorKind:'spider',placeMode:'new',selectedTile:0,selectedActorId:null,zoom:1.25,drag:false,strokeStarted:false,pathStarted:false,history:[],future:[],dirty:false,saveTimer:0};
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const directions=[['0','North'],['1','West'],['2','South'],['3','East']];
const actorTypes=[['chip','Chip','0x6C'],['spider','Spider','0x40'],['spiral','Fireball / Spiral','0x44'],['teeth','Teeth (red lips)','0x54'],['block','Dirt block','0x0A'],['monster','Monster from selected tile','0x40']];
const LG={'.':0,'#':1,c:2,'~':3,f:4,x:0x2C,h:0x2F,E:0x15,S:0x22,B:0x16,R:0x17,G:0x18,Y:0x19,b:0x64,r:0x65,g:0x66,y:0x67,w:0x68,z:0x69,k:0x6A,u:0x6B,',':0x0B,':':0x2D,i:0x0C,'^':0x12,v:0x0D,'<':0x14,'>':0x13,t:0x21,o:0x2A,'@':0x29,p:0x2E,n:0x1E,N:0x1F,'=':0x23,a:0x25,A:0x26};
function sanitize(data){
 const d=clone(data||{});
 if(Array.isArray(d.levels))return d.levels.map(sanitize);
 let w=Number(d.width),h=Number(d.height),tiles=d.tiles;
 if(!Number.isInteger(w)||!Number.isInteger(h)||!Array.isArray(tiles)){
   if(!Array.isArray(d.map))throw new Error('JSON must contain width, height and tiles (or the old map format).');
   const rows=d.map.map(String);w=Math.max(...rows.map(r=>r.length));h=rows.length;tiles=new Array(w*h).fill(0);const actors=[];
   rows.forEach((row,y)=>[...row].forEach((ch,x)=>{if(ch==='P'){tiles[y*w+x]=0;actors.push({id:'chip',type:'chip',variant:'default',x,y,direction:2,speed:500,path:[]})}else tiles[y*w+x]=LG[ch]??0}));
   ;(d.mons||[]).forEach((m,i)=>actors.push({id:m.id||`${m.k||m.type}-${i}`,type:m.k||m.type||'spider',variant:m.variant||'default',x:Number(m.x)||0,y:Number(m.y)||0,direction:Number(m.direction)||2,speed:Number(m.speed)||(m.k==='spider'?MONSTER_DEFAULTS.spiderMoveMs:m.k==='spiral'?MONSTER_DEFAULTS.spiralMoveMs:m.k==='teeth'?MONSTER_DEFAULTS.teethMoveMs:MONSTER_DEFAULTS.genericMonsterMoveMs),path:Array.isArray(m.path)?m.path:[]}));
   d.actors=actors;
 }
 w=clamp(Math.round(w),5,32);h=clamp(Math.round(h),5,32);
 const cleanTiles=new Array(w*h).fill(0);for(let i=0;i<cleanTiles.length;i++){const id=Number(tiles[i]);cleanTiles[i]=Number.isInteger(id)&&id>=0&&id<CC.TILES.length?id:0}
 const actors=Array.isArray(d.actors)?d.actors.map((a,i)=>{const type=['chip','spider','spiral','teeth','monster','block','dirtBlock'].includes(a.type)?(a.type==='dirtBlock'?'block':a.type):'monster';let tileId=Number.isInteger(a.tileId)?a.tileId:null;if(type==='spider')tileId=0x40;else if(type==='spiral')tileId=0x44;else if(type==='teeth')tileId=0x54;return {id:String(a.id||`${type}-${i}`),type,variant:String(a.variant||'red'),tileId,x:clamp(Number(a.x)||0,0,w-1),y:clamp(Number(a.y)||0,0,h-1),direction:[0,1,2,3].includes(Number(a.direction))?Number(a.direction):2,speed:Math.max(100,Math.min(2000,Number(a.speed)||500)),path:Array.isArray(a.path)?a.path.map(p=>({x:clamp(Number(p.x)||0,0,w-1),y:clamp(Number(p.y)||0,0,h-1)})):[],pathMode:String(a.pathMode||'loop'),aiChase:!!a.aiChase,visionRange:Math.max(1,Math.min(32,Number(a.visionRange)||10)),focusLoseDistanceTiles:Math.max(1,Math.min(32,Number(a.focusLoseDistanceTiles)||10)),neverLoseFocus:a.neverLoseFocus===1||a.neverLoseFocus===true,focusMs:Math.max(250,Math.min(60000,Number(a.focusMs)||5000))}}):[];
 const chips=actors.filter(a=>a.type==='chip');
 if(!chips.length)actors.unshift({id:'chip',type:'chip',variant:'default',x:1,y:1,direction:2,speed:500,path:[]});
 if(chips.length>1)actors.splice(actors.findIndex(a=>a.type==='chip')+1,1);
 const rules=d.rules&&typeof d.rules==='object'?d.rules:{};
 const ms=d.monsterSettings&&typeof d.monsterSettings==='object'?d.monsterSettings:(d.settings&&d.settings.monsters&&typeof d.settings.monsters==='object'?d.settings.monsters:{});
 const hiddenDirt=Array.isArray(d.hiddenDirt)?d.hiddenDirt.map(p=>({x:clamp(Number(p.x)||0,0,w-1),y:clamp(Number(p.y)||0,0,h-1),underTile:Number.isInteger(p.underTile)?p.underTile:cleanTiles[(clamp(Number(p.y)||0,0,h-1)*w)+clamp(Number(p.x)||0,0,w-1)]})).filter((p,i,a)=>a.findIndex(q=>q.x===p.x&&q.y===p.y)===i):[];
 return {schema:'chips-custom-level',version:5,title:String(d.title||d.name||'CUSTOM LEVEL'),author:String(d.author||''),timeLimit:Math.max(0,Math.min(999,Number(d.timeLimit??d.time)||200)),requiredChips:Math.max(0,Number(d.requiredChips||cleanTiles.filter(x=>x===2).length)),hint:String(d.hint||''),hintSettings:{triggerTileId:0x2F,offDelayMs:5000},hiddenDirt,hiddenDirtSettings:{triggerTileId:0x24,oncePerMap:true},width:w,height:h,tiles:cleanTiles,actors,rules,monsterSettings:{spiderMoveMs:Math.max(100,Math.min(2000,Number(ms.spiderMoveMs)||800)),spiralMoveMs:Math.max(100,Math.min(2000,Number(ms.spiralMoveMs)||600)),teethMoveMs:Math.max(100,Math.min(2000,Number(ms.teethMoveMs)||400)),genericMonsterMoveMs:Math.max(100,Math.min(2000,Number(ms.genericMonsterMoveMs)||500)),teethFocusMs:Math.max(250,Math.min(60000,Number(ms.teethFocusMs)||5000)),defaultVisionTiles:Math.max(1,Math.min(32,Number(ms.defaultVisionTiles)||10)),focusLoseDistanceTiles:Math.max(1,Math.min(32,Number(ms.focusLoseDistanceTiles)||10))},tileset:TILESET};
}
function tileMeta(id){return CC.TILES[id]||CC.TILES[0]}
function current(){return E.levels[E.slot]}
function makeNew(){const w=20,h=12,t=new Array(w*h).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(x===0||y===0||x===w-1||y===h-1)t[y*w+x]=1;return sanitize({title:'NEW CUSTOM LEVEL',author:'',timeLimit:200,requiredChips:1,hint:'Build your puzzle here.',width:w,height:h,tiles:t,actors:[{id:'chip',type:'chip',variant:'default',x:1,y:1,direction:2,speed:500,path:[]}],rules:{}})}
E.levels=(window.CC_LEVELS||[]).slice(0,9).map(sanitize);while(E.levels.length<9)E.levels.push(makeNew());
function jsonString(level){return JSON.stringify(level,null,2)}
function tileEl(id,scale){const t=tileMeta(id),e=document.createElement('div');e.className='etile'+(t.mask?' sprite':'');e.style.setProperty('--c',t.c);e.style.setProperty('--r',t.r);e.style.setProperty('--z',scale);e.title=`0x${id.toString(16).padStart(2,'0')} · ${t.name}`;return e}
function pathValid(a,L){if(!a||!['spider','spiral','teeth','monster'].includes(a.type))return ['Select a path-enabled monster.'];if(a.type==='spider'&&a.pathMode!=='loop')return [];const p=a.path||[],errs=[];if(p.length<2)errs.push('Add at least two adjacent cells.');const seen=new Set();for(let i=0;i<p.length;i++){const q=p[(i+1)%p.length],pt=p[i],key=`${pt.x},${pt.y}`;if(seen.has(key))errs.push('Path contains a duplicate cell.');seen.add(key);if(Math.abs(pt.x-q.x)+Math.abs(pt.y-q.y)!==1)errs.push(`Path step ${i+1} is not adjacent.`);const id=L.tiles[pt.y*L.width+pt.x];const f=Object.assign({},tileMeta(id),L.rules[String(id)]||{});if(f.wall&&!f.hiddenWall)errs.push(`Path crosses blocked tile ${pt.x},${pt.y}.`)}if(p.length&& (p[0].x!==a.x||p[0].y!==a.y))errs.push('Path must begin at the actor.');return [...new Set(errs)]}
function inRange(x,y,w,h){return Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<w&&y<h}
function validate(L=current()){const errs=[];if(!L.tiles||L.tiles.length!==L.width*L.height)errs.push('Tile array does not match map size.');if(L.actors.filter(a=>a.type==='chip').length!==1)errs.push('Exactly one Chip start is required.');const ids=new Set();for(const a of L.actors){if(ids.has(a.id))errs.push(`Duplicate actor ID: ${a.id}`);ids.add(a.id);if(['spider','spiral','teeth','monster'].includes(a.type)){if(a.type==='spider'&&a.pathMode!=='loop')continue;if(!Number.isInteger(a.tileId)&&a.type==='monster')errs.push(`Monster ${a.id}: missing linked tile ID.`);if(['monster','teeth'].includes(a.type)&&( !Number.isInteger(a.tileId)||!CC.TILES[a.tileId]?.monster))errs.push(`Monster ${a.id}: linked tile must be one of the original monster sprites.`);errs.push(...pathValid(a,L).map(x=>`${a.type} ${a.id}: ${x}`))}}for(const p of L.hiddenDirt||[]){if(!inRange(p.x,p.y,L.width,L.height))errs.push(`Hidden dirt is outside the map at ${p.x},${p.y}.`);const i=p.y*L.width+p.x;if(Number.isInteger(p.underTile)&&(p.underTile<0||p.underTile>=CC.TILES.length))errs.push(`Hidden dirt at ${p.x},${p.y} has an invalid underlying tile.`);const ti=Number.isInteger(L.hiddenDirtSettings?.triggerTileId)?L.hiddenDirtSettings.triggerTileId:0x24;if(L.tiles[i]===ti)errs.push(`Hidden dirt at ${p.x},${p.y} cannot also be the red trigger tile.`);if(L.actors.some(a=>a.x===p.x&&a.y===p.y))errs.push(`Hidden dirt at ${p.x},${p.y} cannot overlap an actor.`)}return [...new Set(errs)]}
function mark(label='Unsaved changes'){E.dirty=true;$('dirtyState').textContent='Unsaved';$('dirtyState').className='dirtyState dirty';$('editStatus').textContent=label;$('editStatus').className='status dirty';clearTimeout(E.saveTimer);E.saveTimer=setTimeout(()=>autoSave(),500)}
function autoSave(){try{localStorage.setItem(LS+E.slot,jsonString(current()));E.dirty=false;$('dirtyState').textContent='Saved';$('dirtyState').className='dirtyState saved';$('editStatus').textContent='Autosaved to this browser.';$('editStatus').className='status good'}catch(e){$('editStatus').textContent='Browser autosave unavailable; use Save JSON file.'}}
function snapshotSlot(slot,label){E.history.push({slot,label,data:jsonString(E.levels[slot])});if(E.history.length>60)E.history.shift();E.future.length=0;updateUndo()}
function snapshot(label){snapshotSlot(E.slot,label)}
function undo(){const h=E.history.pop();if(!h)return;E.future.push({slot:E.slot,data:jsonString(current())});E.slot=h.slot??E.slot;E.levels[E.slot]=sanitize(JSON.parse(h.data));E.selectedActorId=null;renderAll();mark(`Undid: ${h.label}`);updateUndo()}
function redo(){const h=E.future.pop();if(!h)return;E.history.push({label:'Redo',data:jsonString(current())});E.levels[E.slot]=sanitize(JSON.parse(h.data));renderAll();mark('Redid last action.');updateUndo()}
function updateUndo(){$('undoBtn').disabled=!E.history.length;$('redoBtn').disabled=!E.future.length}
function setTool(tool){E.tool=tool;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));if(tool==='hiddenDirt')$('editStatus').textContent='Click a cell to mark it as hidden dirt. It will appear when Chip steps on the red trigger (0x24).';if(tool==='path'){const a=current().actors.find(a=>a.id===E.selectedActorId);if(!a||!['spider','spiral','teeth','monster'].includes(a.type))$('editStatus').textContent='Select a Spider, Fireball/Spiral, Teeth, or custom monster first.';else if(a.type==='spider'&&a.pathMode!=='loop')$('editStatus').textContent='Enable “Use authored path” on the selected Spider first.'}}
function setActorKind(kind){E.actorKind=kind;document.querySelectorAll('.actor-btn').forEach(b=>b.classList.toggle('activeChoice',b.dataset.kind===kind));}
function uniqueId(type){let i=0;while(current().actors.some(a=>a.id===`${type}-${i}`))i++;return `${type}-${i}`}
function hiddenDirtAt(L,x,y){return (L.hiddenDirt||[]).find(p=>p.x===x&&p.y===y)}
function toggleHiddenDirt(index){
 const L=current(),x=index%L.width,y=Math.floor(index/L.width),existing=hiddenDirtAt(L,x,y);
 if(existing){snapshot('Remove hidden dirt');L.hiddenDirt=L.hiddenDirt.filter(p=>!(p.x===x&&p.y===y));mark('Removed hidden dirt overlay.');renderMap();return}
 snapshot('Place hidden dirt');L.hiddenDirt=L.hiddenDirt||[];L.hiddenDirt.push({x,y,underTile:L.tiles[index]});mark('Placed hidden dirt overlay. It will appear when the red trigger fires.');renderMap();
}
function clearHiddenDirt(){const L=current();if(!(L.hiddenDirt||[]).length)return;snapshot('Clear hidden dirt');L.hiddenDirt=[];mark('Cleared hidden dirt overlays.');renderMap()}
function placeActor(x,y){const L=current();if(E.actorKind==='chip'&&L.actors.some(a=>a.type==='chip')){E.selectedActorId=L.actors.find(a=>a.type==='chip').id;E.placeMode='move';return renderAll()}
 snapshot('Place '+E.actorKind);let type=E.actorKind,tileId=null;if(type==='monster'){tileId=Number.isInteger(E.selectedTile)&&CC.TILES[E.selectedTile]?.monster?E.selectedTile:0x40;type='monster'}else if(type==='spider')tileId=0x40;else if(type==='spiral')tileId=0x44;else if(type==='teeth')tileId=0x54;const cfg=current().monsterSettings||MONSTER_DEFAULTS;const a={id:type==='chip'?'chip':uniqueId(type),type,variant:type==='spider'||type==='spiral'||type==='teeth'||type==='monster'?'red':'default',tileId,x,y,direction:2,speed:type==='spider'?(cfg.spiderMoveMs||800):type==='spiral'?(cfg.spiralMoveMs||600):type==='teeth'?(cfg.teethMoveMs||400):(cfg.genericMonsterMoveMs||500),path:['spiral','teeth','monster'].includes(type)?[{x,y}]:[],pathMode:type==='spider'?'ai':'loop',aiChase:type==='spider'||type==='teeth',visionRange:cfg.defaultVisionTiles||10,focusLoseDistanceTiles:cfg.focusLoseDistanceTiles||10,neverLoseFocus:false,focusMs:cfg.teethFocusMs||5000};L.actors.push(a);E.selectedActorId=a.id;mark(`Placed ${type}.`);renderAll()}
function moveSelected(x,y){const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);if(!a)return;$('editStatus').textContent='No actor selected.';snapshot('Move '+a.type);a.x=x;a.y=y;if(['spiral','teeth','monster'].includes(a.type))a.path=[{x,y}];mark(`Moved ${a.type}.`);renderAll()}
function paintAt(index){const L=current(),id=E.tool==='erase'?0:E.selectedTile,hd=hiddenDirtAt(L,index%L.width,Math.floor(index/L.width));if(L.tiles[index]===id&&(!hd||hd.underTile===id))return;if(!E.strokeStarted){snapshot(E.tool==='erase'?'Erase tiles':'Paint tiles');E.strokeStarted=true}L.tiles[index]=id;if(hd)hd.underTile=id;mark(E.tool==='erase'?'Erasing…':'Painting…');renderCell(index)}
function addPathPoint(x,y){const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);if(!a||!['spider','spiral','teeth','monster'].includes(a.type)){setStatus('Select a path-enabled monster to edit its loop.');return}if(a.type==='spider'&&a.pathMode!=='loop'){setStatus('Enable “Use authored path” for this Spider first.');return}if(!a.path?.length){snapshot('Start monster path');a.path=[{x:a.x,y:a.y}];mark('Started monster loop.');renderMap();return}const last=a.path[a.path.length-1],first=a.path[0];if(x===first.x&&y===first.y){if(Math.abs(last.x-first.x)+Math.abs(last.y-first.y)===1){mark('Loop closed.');renderMap();$('editStatus').textContent='Loop is closed; game closes it automatically.'}return}if(a.path.some(p=>p.x===x&&p.y===y)){setStatus('That cell is already in the loop.');return}if(Math.abs(last.x-x)+Math.abs(last.y-y)!==1){setStatus('Path points must be adjacent.');return}if(!E.pathStarted){snapshot('Edit monster path');E.pathStarted=true}a.path.push({x,y});mark('Editing monster loop…');renderMap();renderActorInspector()}
function setStatus(t,kind=''){const el=$('editStatus');el.textContent=t;el.className='status '+kind}
function renderCell(index){const L=current(),cell=$('mapGrid').children[index];if(!cell)return;cell.textContent='';cell.append(tileEl(L.tiles[index],E.zoom));cell.dataset.index=index;const x=index%L.width,y=Math.floor(index/L.width);cell.dataset.x=x;cell.dataset.y=y;if(hiddenDirtAt(L,x,y)){const hd=document.createElement('span');hd.className='hidden-dirt-dot';hd.textContent='D';hd.title='Hidden dirt: appears when the red trigger is activated';cell.append(hd)}L.actors.filter(a=>a.x===x&&a.y===y).forEach(a=>renderActorOverlay(cell,a));if(E.selectedActorId){const a=L.actors.find(a=>a.id===E.selectedActorId);if(a&&['spider','spiral','teeth','monster'].includes(a.type)&&a.pathMode==='loop')renderPathDots(cell,x,y,a.path||[])}}
function renderActorOverlay(cell,a){const idx= a.type==='chip'?0x6C+((a.direction??2)&3):a.type==='spider'?0x40+((a.direction??2)&3):a.type==='spiral'?0x44+((a.direction??2)&3):a.type==='teeth'?0x54+((a.direction??2)&3):a.type==='monster'?(Number.isInteger(a.tileId)?(a.tileId+((a.direction??2)&3)):0x40):0x0A;const o=tileEl(idx,E.zoom);o.className+=' actor-overlay'+(a.id===E.selectedActorId?' selected-actor':'');o.dataset.actorId=a.id;o.onclick=e=>{e.stopPropagation();E.selectedActorId=a.id;renderAll();};cell.append(o);const label=document.createElement('span');label.className='actor-label';label.textContent=a.type[0].toUpperCase();cell.append(label)}
function renderPathDots(cell,x,y,path){const i=path.findIndex(p=>p.x===x&&p.y===y);if(i>=0){const d=document.createElement('span');d.className='path-dot'+(i===0?' closed':'');d.textContent=i+1;cell.append(d)}}
function renderMap(){const L=current(),g=$('mapGrid');g.innerHTML='';g.style.setProperty('--cols',L.width);g.style.setProperty('--zoom',E.zoom);for(let i=0;i<L.tiles.length;i++){const cell=document.createElement('button');cell.className='map-cell';cell.addEventListener('pointerdown',e=>{e.preventDefault();E.drag=true;handleMapAction(i)});cell.addEventListener('pointerenter',()=>{if(E.drag&&(E.tool==='paint'||E.tool==='erase'))paintAt(i)});g.append(cell);renderCell(i)};document.body.dataset.tool=E.tool;renderActorList();renderPathInfo();}
function handleMapAction(index){const L=current(),x=index%L.width,y=Math.floor(index/L.width);if(E.tool==='paint'||E.tool==='erase')paintAt(index);else if(E.tool==='hiddenDirt'){toggleHiddenDirt(index)}else if(E.tool==='actor'){if(E.placeMode==='new')placeActor(x,y);else moveSelected(x,y)}else if(E.tool==='path')addPathPoint(x,y)}
function renderActorList(){const box=$('actorInspector');box.innerHTML='';const L=current();const list=document.createElement('div');list.className='actor-list';L.actors.forEach(a=>{const row=document.createElement('div');row.className='actor-row'+(a.id===E.selectedActorId?' selected':'');const name=document.createElement('button');name.textContent=`${a.type} · ${a.id}`;name.onclick=()=>{E.selectedActorId=a.id;renderAll()};row.append(name);const del=document.createElement('button');del.textContent='×';del.title='Delete actor';del.onclick=()=>{snapshot('Delete actor');L.actors=L.actors.filter(x=>x.id!==a.id);if(E.selectedActorId===a.id)E.selectedActorId=null;mark('Deleted actor.');renderAll()};row.append(del);list.append(row)});box.append(list);renderActorInspector()}
function renderActorInspector(){const box=$('actorInspector');const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);const title=document.createElement('div');title.className='inspector-title';title.textContent=a?'Selected actor':'No actor selected';box.append(title);if(!a)return;const wrap=document.createElement('div');wrap.className='inspector-grid';
 const type=document.createElement('label');type.innerHTML='Type<select id="aType"><option value="chip">Chip</option><option value="spider">Spider</option><option value="spiral">Fireball / Spiral</option><option value="teeth">Teeth (red lips)</option><option value="monster">Custom monster</option><option value="block">Dirt block</option></select></label>';wrap.append(type);
 const typeSel=type.querySelector('select');typeSel.value=a.type;typeSel.onchange=()=>{snapshot('Change actor type');a.type=typeSel.value;a.tileId=a.type==='spider'?0x40:a.type==='spiral'?0x44:a.type==='teeth'?0x54:a.type==='monster'?(E.selectedTile&&CC.TILES[E.selectedTile]?.monster?E.selectedTile:0x40):a.tileId;a.path=['spider','spiral','teeth','monster'].includes(a.type)?[{x:a.x,y:a.y}]:[];a.pathMode=a.type==='spider'?'ai':(['spiral','teeth','monster'].includes(a.type)?'loop':'');a.aiChase=a.type==='spider'||a.type==='teeth'?true:a.aiChase;a.visionRange=a.visionRange||MONSTER_DEFAULTS.defaultVisionTiles;a.focusLoseDistanceTiles=a.focusLoseDistanceTiles||MONSTER_DEFAULTS.focusLoseDistanceTiles;a.neverLoseFocus=!!a.neverLoseFocus;a.focusMs=a.focusMs||MONSTER_DEFAULTS.teethFocusMs;mark('Changed actor type.');renderAll()};
 const tileLabel=document.createElement('label');tileLabel.innerHTML='Linked tile<input id="aTile" type="number" min="64" max="99" value="'+(a.tileId??'')+'"></label>';tileLabel.querySelector('input').onchange=e=>{const id=clamp(+e.target.value,64,99);if(!CC.TILES[id]?.monster){setStatus('Choose a real monster tile ID (0x40–0x63, excluding 0x58–0x5B).');e.target.value=a.tileId??64;return}snapshot('Change linked monster tile');a.tileId=id;if(['monster','teeth'].includes(a.type)){a.type=a.type;mark('Changed linked monster tile.');renderAll()}};if(['monster','teeth'].includes(a.type))wrap.append(tileLabel);
 const variant=document.createElement('label');variant.innerHTML='Variant<select><option value="red">Red</option><option value="yellow">Yellow</option><option value="default">Default</option></select></label>';variant.querySelector('select').value=a.variant;variant.querySelector('select').onchange=e=>{snapshot('Change actor variant');a.variant=e.target.value;mark('Changed actor variant.');renderAll()};wrap.append(variant);
 const x=document.createElement('label');x.innerHTML='X<input type="number" min="0" max="31" value="'+a.x+'"></label>';x.querySelector('input').onchange=e=>moveActorField(a,'x',e.target.value);wrap.append(x);const y=document.createElement('label');y.innerHTML='Y<input type="number" min="0" max="31" value="'+a.y+'"></label>';y.querySelector('input').onchange=e=>moveActorField(a,'y',e.target.value);wrap.append(y);
 const dir=document.createElement('label');dir.innerHTML='Direction<select>'+directions.map(d=>`<option value="${d[0]}">${d[1]}</option>`).join('')+'</select></label>';dir.querySelector('select').value=a.direction;dir.querySelector('select').onchange=e=>{snapshot('Change actor direction');a.direction=+e.target.value;mark('Changed direction.');renderAll()};wrap.append(dir);
 const speed=document.createElement('label');speed.innerHTML='Move speed (ms/tile)<input type="number" min="100" max="2000" value="'+a.speed+'"><small>Lower = faster</small></label>';speed.querySelector('input').onchange=e=>{snapshot('Change actor speed');a.speed=clamp(+e.target.value,100,2000);mark('Changed speed.');renderAll()};wrap.append(speed);
 if(['teeth','monster'].includes(a.type)){const ai=document.createElement('label');ai.className='rule-check';ai.innerHTML='<input type="checkbox"> Chase Chip when visible';ai.querySelector('input').checked=!!a.aiChase;ai.querySelector('input').onchange=e=>{snapshot('Change monster AI');a.aiChase=e.target.checked;mark('Changed chase behavior.');};wrap.append(ai);const vr=document.createElement('label');vr.innerHTML='Vision / focus range (tiles)<input type="number" min="1" max="32" value="'+(a.visionRange||10)+'">';vr.querySelector('input').onchange=e=>{snapshot('Change vision range');a.visionRange=clamp(+e.target.value,1,32);mark('Changed vision range.');};wrap.append(vr);const fl=document.createElement('label');fl.innerHTML='Focus distance (tiles)<input type="number" min="1" max="32" value="'+(a.focusLoseDistanceTiles||10)+'">';fl.querySelector('input').onchange=e=>{snapshot('Change focus distance');a.focusLoseDistanceTiles=clamp(+e.target.value,1,32);mark('Changed focus distance.');};wrap.append(fl);const nf=document.createElement('label');nf.className='rule-check';nf.innerHTML='<input type="checkbox"> Never lose focus after seeing Chip';nf.querySelector('input').checked=!!a.neverLoseFocus;nf.querySelector('input').onchange=e=>{snapshot('Change focus persistence');a.neverLoseFocus=e.target.checked;mark(e.target.checked?'Monster will keep focus after first sighting.':'Monster can lose focus normally.');renderAll()};wrap.append(nf);if(a.type==='teeth'){const ft=document.createElement('label');ft.innerHTML='Focus duration (ms)<input type="number" min="250" max="60000" value="'+(a.focusMs||5000)+'">';ft.querySelector('input').onchange=e=>{snapshot('Change Teeth focus duration');a.focusMs=clamp(+e.target.value,250,60000);mark('Changed Teeth focus duration.');};wrap.append(ft)}}
 box.append(wrap);
 if(a.type==='spider'){const pm=document.createElement('label');pm.className='rule-check';pm.innerHTML='<input type="checkbox"> Use authored path (optional)';const pc=pm.querySelector('input');pc.checked=a.pathMode==='loop';pc.onchange=e=>{snapshot('Change spider path mode');a.pathMode=e.target.checked?'loop':'ai';if(e.target.checked&&!a.path?.length)a.path=[{x:a.x,y:a.y}];mark(e.target.checked?'Spider authored path enabled.':'Spider A* AI restored.');renderAll()};wrap.append(pm)}
 if(['spider','spiral','teeth','monster'].includes(a.type)&& (a.type!=='spider'||a.pathMode==='loop')){const status=pathValid(a,L);const p=document.createElement('div');p.className='inspector-title';p.innerHTML=`Monster path: <b>${a.path?.length||0}</b> point(s) · ${status.length?'Needs attention':'Valid closed loop'}`;box.append(p);const note=document.createElement('div');note.className='path-note';note.textContent=a.type==='teeth'?'Teeth chase Chip from any visible direction, keep focus for 5 seconds after the last sighting, then return to their loop.':a.type==='spider'?'Spider uses the restored A* AI by default. Enable authored path to replace the AI with a fixed loop.':'This monster is linked directly to its selected tileset sprite. The game follows the authored path loop.';box.append(note);const buttons=document.createElement('div');buttons.className='path-tools';const clear=document.createElement('button');clear.textContent='Clear path';clear.onclick=()=>{snapshot('Clear monster path');a.path=[{x:a.x,y:a.y}];mark('Cleared monster path.');renderAll()};const reset=document.createElement('button');reset.textContent='Start at actor';reset.onclick=()=>{snapshot('Restart monster path');a.path=[{x:a.x,y:a.y}];mark('Restarted monster path.');renderAll()};buttons.append(clear,reset);box.append(buttons)} }

function moveActorField(a,key,v){const L=current();snapshot('Move actor');a[key]=clamp(Number(v)||0,0,L[key==='x'?'width':'height']-1);if(['spider','spiral','teeth','monster'].includes(a.type)&&a.pathMode==='loop')a.path=[{x:a.x,y:a.y}];mark('Moved actor.');renderAll()}
function renderPathInfo(){const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId&&['spider','spiral','teeth','monster'].includes(a.type));if(a&&E.tool==='path'){const errs=pathValid(a,L);setStatus(errs.length?errs[0]:'Path loop is valid. Click adjacent cells to extend it.','')} }
function buildPalette(){const box=$('palette');box.innerHTML='';const q=$('paletteSearch').value.trim().toLowerCase(),group=$('paletteGroup').value;const filtered=CC.TILES.filter(t=>{if(group==='terrain'&&t.id>=64)return false;if(group==='creatures'&&!t.monster)return false;if(group==='items'&&(t.id<100||t.id>=108))return false;if(group==='devices'&&(t.id>=64||[2,0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F].includes(t.id)))return false;if(group==='chip'&&(t.id<108))return false;return !q||t.name.toLowerCase().includes(q)||`0x${t.id.toString(16).padStart(2,'0')}`.includes(q)||String(t.id)===q});for(const t of filtered){const b=document.createElement('button');b.className='palette-btn'+(t.id===E.selectedTile?' selected':'');b.title=`0x${t.id.toString(16).padStart(2,'0')} · ${t.name}`;b.onclick=()=>{E.selectedTile=t.id;if(t.monster)E.actorKind='monster';setTool('paint');renderAll()};const p=tileEl(t.id,1.35);p.className+=' preview';b.append(p);const id=document.createElement('span');id.className='id';id.textContent='0x'+t.id.toString(16).padStart(2,'0');const nm=document.createElement('span');nm.className='name';nm.textContent=t.name;b.append(id,nm);box.append(b)}$('paletteCount').textContent=`${filtered.length} tile${filtered.length===1?'':'s'} shown`}
function ruleValue(L,id,key){return L.rules[String(id)]?.[key]??tileMeta(id)[key]??false}
function setRule(id,key,val){const L=current(),base=tileMeta(id),obj=L.rules[String(id)]||{},old=obj[key];let same=String(old??'')===String(val??'');if(same)return;snapshot('Change tile property');const baseVal=base[key];if(val===null||val===undefined||String(val)===String(baseVal))delete obj[key];else obj[key]=val;if(!Object.keys(obj).length)delete L.rules[String(id)];else L.rules[String(id)]=obj;mark('Changed tile property.')}
function renderTileRules(){const id=E.selectedTile,t=tileMeta(id),L=current(),box=$('tileRules');box.innerHTML='';const flags=[['walk','Walkable'],['wall','Wall'],['danger','Dangerous'],['water','Water'],['fire','Fire'],['ice','Ice / slide'],['destructible','Destructible'],['item','Collectible'],['button','Button'],['monster','Monster tile'],['block','Block tile'],['hiddenWall','Hidden wall']];for(const [k,label] of flags){const l=document.createElement('label');l.className='rule-check';const c=document.createElement('input');c.type='checkbox';c.checked=!!ruleValue(L,id,k);c.onchange=()=>{setRule(id,k,c.checked);renderTileRules()};l.append(c,label);box.append(l)}
 const door=document.createElement('select');door.innerHTML='<option value="">Door: none</option><option value="c">Door: cyan</option><option value="r">Door: red</option><option value="g">Door: green</option><option value="y">Door: yellow</option>';door.value=L.rules[String(id)]?.door??t.door??'';door.onchange=()=>{setRule(id,'door',door.value||null);renderTileRules()};box.append(door);
 const force=document.createElement('select');force.innerHTML='<option value="">Force: none</option><option value="0">Force: north</option><option value="1">Force: west</option><option value="2">Force: south</option><option value="3">Force: east</option><option value="-1">Force: random</option>';force.value=L.rules[String(id)]?.force??(t.force==null?'':String(t.force));force.onchange=()=>{setRule(id,'force',force.value===''?null:Number(force.value));renderTileRules()};box.append(force);
 const card=$('selectedTile');card.innerHTML='';const prev=document.createElement('div');prev.className='selected-preview';prev.append(tileEl(id,2));const text=document.createElement('div');text.className='tile-text';text.innerHTML=`<strong>0x${id.toString(16).padStart(2,'0')} · ${t.name}</strong><small>Column ${t.c} · Row ${t.r} · ${t.mask?'sprite with atlas mask':'normal atlas tile'}</small>`;card.append(prev,text);const qa=$('monsterQuickAdd');qa.innerHTML='';if(t.monster){const b=document.createElement('button');b.className='primary';b.textContent=`Use ${t.name} as path monster`;b.onclick=()=>{E.actorKind='monster';E.placeMode='new';setTool('actor');document.querySelectorAll('.actor-btn').forEach(x=>x.classList.toggle('activeChoice',x.dataset.kind==='monster'));setStatus(`Selected ${t.name}. Click a map cell to place it, then switch to Monster path.`)};qa.append(b);const n=document.createElement('small');n.textContent='This stores the exact tileset ID on the actor and its path in the JSON map.';qa.append(n)}}
function renderTop(){const L=current();$('slotSelect').value=String(E.slot);$('titleInput').value=L.title;$('authorInput').value=L.author;$('timeInput').value=L.timeLimit;$('chipsInput').value=L.requiredChips;$('hintInput').value=L.hint;$('widthInput').value=L.width;$('heightInput').value=L.height;$('mapTitle').textContent=L.title||'Map';$('hiddenDirtCount').textContent=(L.hiddenDirt||[]).length+' hidden dirt tile'+((L.hiddenDirt||[]).length===1?'':'s')}
const MONSTER_CONFIG_FIELDS=[['cfgSpider','spiderMoveMs',800],['cfgSpiral','spiralMoveMs',600],['cfgTeeth','teethMoveMs',400],['cfgFocus','teethFocusMs',5000,'seconds'],['cfgVision','defaultVisionTiles',10],['cfgFocusDistance','focusLoseDistanceTiles',10]];
function syncMonsterConfigUI(){const cfg=current().monsterSettings||{};for(const [id,key,def,kind] of MONSTER_CONFIG_FIELDS){const input=$(id);if(!input)continue;input.value=kind==='seconds'?(Number(cfg[key]??def)/1000):Number(cfg[key]??def)}}
function renderAll(){renderTop();buildPalette();renderMap();renderTileRules();updateUndo();syncMonsterConfigUI()}
function slotOptions(){const s=$('slotSelect');s.innerHTML='';for(let i=0;i<9;i++){const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} · ${E.levels[i].title}`;s.append(o)}s.value=String(E.slot)}
function commitField(id,key,transform=x=>x){const input=$(id);input.onchange=()=>{const L=current(),v=transform(input.value);if(String(L[key])===String(v))return;snapshot('Edit '+key);L[key]=v;mark('Changed '+key+'.');renderTop()};}
function resizeMap(){const L=current(),w=clamp(+$('widthInput').value,5,32),h=clamp(+$('heightInput').value,5,32);if(w===L.width&&h===L.height)return;snapshot('Resize map');const nt=new Array(w*h).fill(0);for(let y=0;y<Math.min(h,L.height);y++)for(let x=0;x<Math.min(w,L.width);x++)nt[y*w+x]=L.tiles[y*L.width+x];L.width=w;L.height=h;L.tiles=nt;L.hiddenDirt=(L.hiddenDirt||[]).filter(p=>p.x<w&&p.y<h);L.actors.forEach(a=>{a.x=clamp(a.x,0,w-1);a.y=clamp(a.y,0,h-1);a.path=(a.path||[]).filter(p=>p.x<w&&p.y<h);if(['spiral','teeth','monster'].includes(a.type))a.path=[{x:a.x,y:a.y}]});mark('Resized map.');renderAll()}
function exportLevel(){const data=jsonString(current()),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');const name=(current().title||'custom-level').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'custom-level';a.href=URL.createObjectURL(blob);a.download=name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);try{localStorage.setItem(LS+E.slot,data)}catch(e){}E.dirty=false;$('dirtyState').textContent='Saved';$('dirtyState').className='dirtyState saved';setStatus('JSON file saved.', 'good')}
function exportPack(){const pack={schema:'chips-custom-level-pack',version:2,levels:E.levels.map(sanitize),tileset:TILESET};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)],{type:'application/json'}));a.download='chips-custom-level-pack.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus('1–9 JSON pack saved.','good')}
async function importFile(file){const d=JSON.parse(await file.text());const items=Array.isArray(d.levels)?d.levels:[d];let loaded=0;for(let i=0;i<items.length&&E.slot+i<9;i++){E.levels[E.slot+i]=sanitize(items[i]);loaded++}E.history=[];E.future=[];E.selectedActorId=null;renderAll();autoSave();setStatus(`Imported ${loaded} level${loaded===1?'':'s'} starting at slot ${E.slot+1}.`,'good')}
function loadSlot(i){if(E.dirty)autoSave();E.slot=i;E.selectedActorId=null;E.history=[];E.future=[];let local=null;try{local=localStorage.getItem(LS+i)}catch(e){}if(local){try{E.levels[i]=sanitize(JSON.parse(local));setStatus(`Loaded browser-saved level ${i+1}.`,'good')}catch(e){}}renderAll()}
function createNew(){snapshot('Create new map');E.levels[E.slot]=makeNew();E.selectedActorId=null;mark('New map created.');renderAll()}
function duplicate(){const next=Math.min(8,E.slot+1);snapshotSlot(next,'Duplicate map');E.levels[next]=sanitize(current());E.levels[next].title=(current().title||'LEVEL')+' COPY';E.slot=next;E.selectedActorId=null;mark(`Duplicated map to slot ${next+1}.`);renderAll()}
function playMap(){const errs=validate();if(errs.length){alert('Fix these editor issues first:\n\n'+errs.join('\n'));return}try{localStorage.setItem('ccPendingLevel',jsonString(current()))}catch(e){alert('Could not hand the map to the game browser storage. Save the JSON instead.');return}window.location.href='index.html'}
function copyJSON(){if(!navigator.clipboard)return setStatus('Clipboard unavailable; use Save JSON file.');navigator.clipboard.writeText(jsonString(current())).then(()=>setStatus('JSON copied to clipboard.','good')).catch(()=>setStatus('Clipboard unavailable; use Save JSON file.'))}
function setZoom(v){E.zoom=clamp(Number(v),.75,2.5);$('zoomRange').value=E.zoom;$('zoomLabel').textContent=Math.round(E.zoom*100)+'%';renderMap()}
function init(){
 setActorKind('spider');slotOptions();renderAll();
 // Global monster defaults used for newly placed/custom actors.
 for(const [id,key,def,kind] of MONSTER_CONFIG_FIELDS){const input=$(id);if(!input)continue;input.onchange=()=>{const before=current().monsterSettings||{};snapshot('Change monster defaults');const v=Number(input.value)||def;const value=kind==='seconds'?clamp(v*1000,250,60000):clamp(v,1,32);if(['spiderMoveMs','spiralMoveMs','teethMoveMs'].includes(key))current().monsterSettings=Object.assign({},before,{[key]:clamp(v,100,2000)});else current().monsterSettings=Object.assign({},before,{[key]:value});window.CC_MONSTER_CONFIG=Object.assign({},window.CC_MONSTER_CONFIG||{},current().monsterSettings);mark('Monster tuning updated.');renderAll()};}
 document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
 document.querySelectorAll('.actor-btn').forEach(b=>b.onclick=()=>setActorKind(b.dataset.kind));
 $('placeNewBtn').onclick=()=>{E.placeMode='new';$('placeNewBtn').className='activeChoice';$('moveSelectedBtn').className='';setTool('actor')};
 $('moveSelectedBtn').onclick=()=>{E.placeMode='move';$('placeNewBtn').className='';$('moveSelectedBtn').className='activeChoice';setTool('actor')};
 $('slotSelect').onchange=e=>loadSlot(+e.target.value);
 $('saveBtn').onclick=exportLevel;$('saveDownloadBtn').onclick=exportLevel;$('exportPackBtn').onclick=exportPack;$('copyBtn').onclick=copyJSON;$('playMapBtn').onclick=playMap;$('playGameBtn').onclick=()=>location.href='index.html';
 $('newBtn').onclick=createNew;$('duplicateBtn').onclick=duplicate;$('loadSavedBtn').onclick=()=>loadSlot(E.slot);$('resizeBtn').onclick=resizeMap;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('clearHiddenDirtBtn').onclick=clearHiddenDirt;$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{const f=e.target.files[0];if(f)importFile(f).catch(err=>alert('Could not import JSON.\n\n'+err.message));e.target.value=''};
 commitField('titleInput','title',x=>x.trim()||'CUSTOM LEVEL');commitField('authorInput','author',x=>x.trim());commitField('timeInput','timeLimit',x=>clamp(+x||0,0,999));commitField('chipsInput','requiredChips',x=>Math.max(0,+x||0));commitField('hintInput','hint');
 $('paletteSearch').oninput=buildPalette;$('paletteGroup').onchange=buildPalette;$('zoomRange').oninput=e=>setZoom(e.target.value);$('zoomOut').onclick=()=>setZoom(E.zoom-.1);$('zoomIn').onclick=()=>setZoom(E.zoom+.1);
 window.addEventListener('pointerup',()=>{E.drag=false;E.strokeStarted=false;E.pathStarted=false});
 window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();exportLevel()}});
 window.addEventListener('beforeunload',()=>{if(E.dirty)autoSave()});
}
const actorBox=$('actorButtons');for(const [type,label,hex] of actorTypes){const b=document.createElement('button');b.className='actor-btn';b.dataset.kind=type;b.innerHTML=`<span class="mini"></span><span>${label}<br><small>${hex}</small></span>`;const mini=b.querySelector('.mini');mini.append(tileEl(+hex,1));actorBox.append(b)}
init();
})();
