(()=>{'use strict';
const TILESET=window.CC_TILESET_INFO={name:"Chip's Challenge CC1 112-tile atlas",file:'tiles.png',tileSize:32,atlasWidth:416,atlasHeight:512,columns:13,rows:16,tileCount:112};
const MONSTER_DEFAULTS=window.CC_MONSTER_CONFIG=Object.assign({spiderMoveMs:800,spiralMoveMs:600,gliderMoveMs:450,teethMoveMs:400,genericMonsterMoveMs:500,teethFocusMs:5000,defaultVisionTiles:10,focusLoseDistanceTiles:10},window.CC_MONSTER_CONFIG||{});
const LS='chips-editor-slot-';
const EDIT_VIEW_TILES=32; // minimum visible tile window; expands only when the viewport can show more

const E={slot:0,tool:'paint',actorKind:'spider',placeMode:'new',selectedTile:0,selectedActorId:null,zoom:1.25,drag:false,strokeStarted:false,pathStarted:false,pathSlot:0,viewX:0,viewY:0,viewCols:EDIT_VIEW_TILES,viewRows:EDIT_VIEW_TILES,viewReady:false,history:[],future:[],dirty:false,saveTimer:0};
const MAX_PATHS=6,MAX_WAYPOINTS=50,GLIDER_TRIGGER_TILE=0x27,GLIDER_STATION_TILE=0x2B;
const MONSTER_TYPES=new Set(['spider','spiral','teeth','monster','glider']);
const $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const directions=[['0','North'],['1','West'],['2','South'],['3','East']];
const actorTypes=[['chip','Chip','0x6C'],['spider','Spider','0x40'],['spiral','Fireball / Spiral','0x44'],['glider','Glider','0x50'],['teeth','Teeth (red lips)','0x54'],['block','Dirt block','0x0A'],['monster','Monster from selected tile','0x40']];
const LG={'.':0,'#':1,c:2,'~':3,f:4,x:0x2C,h:0x2F,E:0x15,S:0x22,B:0x16,R:0x17,G:0x18,Y:0x19,b:0x64,r:0x65,g:0x66,y:0x67,w:0x68,z:0x69,k:0x6A,u:0x6B,',':0x0B,':':0x2D,i:0x0C,'^':0x12,v:0x0D,'<':0x14,'>':0x13,t:0x21,o:0x2A,'@':0x29,p:0x2E,n:0x1E,N:0x1F,'=':0x23,a:0x25,A:0x26};
function sanitize(data){
 const d=clone(data||{});
 if(Array.isArray(d.levels))return d.levels.map(sanitize);
 let w=Number(d.width),h=Number(d.height),tiles=d.tiles;
 if(!Number.isInteger(w)||!Number.isInteger(h)||!Array.isArray(tiles)){
   if(!Array.isArray(d.map))throw new Error('JSON must contain width, height and tiles (or the old map format).');
   const rows=d.map.map(String);w=Math.max(...rows.map(r=>r.length));h=rows.length;tiles=new Array(w*h).fill(0);const actors=[];
   rows.forEach((row,y)=>[...row].forEach((ch,x)=>{if(ch==='P'){tiles[y*w+x]=0;actors.push({id:'chip',type:'chip',variant:'default',x,y,direction:2,speed:500,path:[]})}else tiles[y*w+x]=LG[ch]??0}));
   ;(d.mons||[]).forEach((m,i)=>actors.push({id:m.id||`${m.k||m.type}-${i}`,type:m.k||m.type||'spider',variant:m.variant||'default',x:Number(m.x)||0,y:Number(m.y)||0,direction:Number(m.direction)||2,speed:Number(m.speed)||(m.k==='spider'?MONSTER_DEFAULTS.spiderMoveMs:m.k==='spiral'?MONSTER_DEFAULTS.spiralMoveMs:m.k==='teeth'?MONSTER_DEFAULTS.teethMoveMs:MONSTER_DEFAULTS.genericMonsterMoveMs),path:Array.isArray(m.path)?m.path:[]}));
   d.actors=actors;
 }
 w=clamp(Math.round(w),5,992);h=clamp(Math.round(h),5,992);
 const cleanTiles=new Array(w*h).fill(0);for(let i=0;i<cleanTiles.length;i++){const id=Number(tiles[i]);cleanTiles[i]=Number.isInteger(id)&&id>=0&&id<CC.TILES.length?id:0}
 const actors=Array.isArray(d.actors)?d.actors.map((a,i)=>{const type=['chip','spider','spiral','teeth','monster','glider','block','dirtBlock'].includes(a.type)?(a.type==='dirtBlock'?'block':a.type):'monster';let tileId=Number.isInteger(a.tileId)?a.tileId:null;if(type==='spider')tileId=0x40;else if(type==='spiral')tileId=0x44;else if(type==='glider')tileId=0x50;else if(type==='teeth')tileId=0x54;const linked=Number.isInteger(tileId)&&CC.TILES[tileId];const monsterKind=linked?.monsterKind||'';const maxPoints=(type==='monster'||monsterKind==='glider')?MAX_WAYPOINTS:256;const waypointList=v=>Array.isArray(v)?v.slice(0,maxPoints).map(p=>({x:clamp(Number(p.x)||0,0,w-1),y:clamp(Number(p.y)||0,0,h-1)})):[];const legacyPath=waypointList(a.path);let waypointPaths=Array.isArray(a.waypointPaths)?a.waypointPaths.slice(0,MAX_PATHS).map(waypointList):[];if(!waypointPaths.length&&legacyPath.length)waypointPaths=[legacyPath];while(waypointPaths.length<MAX_PATHS)waypointPaths.push([]);let railPaths=monsterKind==='glider'?(Array.isArray(a.railPaths)?a.railPaths.slice(0,MAX_PATHS).map(waypointList):waypointPaths.map(x=>x.slice())):[];while(railPaths.length<MAX_PATHS)railPaths.push([]);if(monsterKind==='glider'&&!railPaths.some(p=>p.length)&&legacyPath.length)railPaths[0]=legacyPath.slice();const pathSlot=clamp(Number(a.pathSlot??a.railPathSlot)||0,0,MAX_PATHS-1);const path=monsterKind==='glider'?railPaths[pathSlot]:waypointPaths[pathSlot];const pathMode=String(a.pathMode||(monsterKind==='glider'?'rail':type==='spider'?'ai':'loop'));const pathBehavior=(a.pathBehavior==='loop'||a.pathBehavior==='sequential')?a.pathBehavior:((monsterKind==='glider'||type==='monster')?'sequential':'loop');const loopFromStart=a.loopFromStart===true;const continuousEndBehavior=a.continuousEndBehavior==='stay'?'stay':'return';const defaultTrigger=(type==='monster')?'none':(monsterKind==='glider'?'tan':'none');const buttonTrigger=['none','tan','red','both'].includes(a.buttonTrigger)?a.buttonTrigger:defaultTrigger;return {id:String(a.id||`${type}-${i}`),type,variant:String(a.variant||'red'),tileId,x:clamp(Number(a.x)||0,0,w-1),y:clamp(Number(a.y)||0,0,h-1),direction:[0,1,2,3].includes(Number(a.direction))?Number(a.direction):2,speed:Math.max(100,Math.min(2000,Number(a.speed)||500)),path,pathSlot,pathMode,pathBehavior,loopFromStart,continuousEndBehavior,aiChase:!!a.aiChase,visionRange:Math.max(1,Math.min(32,Number(a.visionRange)||10)),focusLoseDistanceTiles:Math.max(1,Math.min(32,Number(a.focusLoseDistanceTiles)||10)),neverLoseFocus:a.neverLoseFocus===1||a.neverLoseFocus===true,focusMs:Math.max(250,Math.min(60000,Number(a.focusMs)||5000)),buttonBehavior:a.buttonBehavior==='station'?'station':'freeze',buttonTrigger,waypointPaths,railPaths,railPathSlot:pathSlot}}):[];
 const chips=actors.filter(a=>a.type==='chip');
 if(!chips.length)actors.unshift({id:'chip',type:'chip',variant:'default',x:1,y:1,direction:2,speed:500,path:[]});
 if(chips.length>1)actors.splice(actors.findIndex(a=>a.type==='chip')+1,1);
 const rules=d.rules&&typeof d.rules==='object'?d.rules:{};
 const ms=d.monsterSettings&&typeof d.monsterSettings==='object'?d.monsterSettings:(d.settings&&d.settings.monsters&&typeof d.settings.monsters==='object'?d.settings.monsters:{});
 const hiddenDirt=Array.isArray(d.hiddenDirt)?d.hiddenDirt.map(p=>({x:clamp(Number(p.x)||0,0,w-1),y:clamp(Number(p.y)||0,0,h-1),underTile:Number.isInteger(p.underTile)?p.underTile:cleanTiles[(clamp(Number(p.y)||0,0,h-1)*w)+clamp(Number(p.x)||0,0,w-1)]})).filter((p,i,a)=>a.findIndex(q=>q.x===p.x&&q.y===p.y)===i):[];
 return {schema:'chips-custom-level',version:5,title:String(d.title||d.name||'CUSTOM LEVEL'),author:String(d.author||''),timeLimit:Math.max(0,Math.min(999,Number(d.timeLimit??d.time)||200)),requiredChips:Math.max(0,Number(d.requiredChips||cleanTiles.filter(x=>x===2).length)),hint:String(d.hint||''),hintSettings:{triggerTileId:0x2F,offDelayMs:5000},hiddenDirt,hiddenDirtSettings:{triggerTileId:0x24,oncePerMap:true},width:w,height:h,tiles:cleanTiles,actors,rules,monsterSettings:{spiderMoveMs:Math.max(100,Math.min(2000,Number(ms.spiderMoveMs)||800)),spiralMoveMs:Math.max(100,Math.min(2000,Number(ms.spiralMoveMs)||600)),gliderMoveMs:Math.max(100,Math.min(2000,Number(ms.gliderMoveMs)||450)),teethMoveMs:Math.max(100,Math.min(2000,Number(ms.teethMoveMs)||400)),genericMonsterMoveMs:Math.max(100,Math.min(2000,Number(ms.genericMonsterMoveMs)||500)),teethFocusMs:Math.max(250,Math.min(60000,Number(ms.teethFocusMs)||5000)),defaultVisionTiles:Math.max(1,Math.min(32,Number(ms.defaultVisionTiles)||10)),focusLoseDistanceTiles:Math.max(1,Math.min(32,Number(ms.focusLoseDistanceTiles)||10))},tileset:TILESET};
}
function tileMeta(id){return CC.TILES[id]||CC.TILES[0]}
function current(){return E.levels[E.slot]}
function makeNew(){const w=20,h=12,t=new Array(w*h).fill(0);for(let y=0;y<h;y++)for(let x=0;x<w;x++)if(x===0||y===0||x===w-1||y===h-1)t[y*w+x]=1;return sanitize({title:'NEW CUSTOM LEVEL',author:'',timeLimit:200,requiredChips:1,hint:'Build your puzzle here.',width:w,height:h,tiles:t,actors:[{id:'chip',type:'chip',variant:'default',x:1,y:1,direction:2,speed:500,path:[]}],rules:{}})}
E.levels=(window.CC_LEVELS||[]).slice(0,9).map(sanitize);while(E.levels.length<9)E.levels.push(makeNew());
function jsonString(level){return JSON.stringify(level,null,2)}
function tileEl(id,scale){const t=tileMeta(id),e=document.createElement('div');e.className='etile'+(t.mask?' sprite':'');e.style.setProperty('--c',t.c);e.style.setProperty('--r',t.r);e.style.setProperty('--z',scale);e.title=`0x${id.toString(16).padStart(2,'0')} · ${t.name}`;return e}
function actorMonsterKind(a){if(!a)return '';if(a.type==='glider')return 'glider';const id=Number.isInteger(a.tileId)?a.tileId:null;return id!=null?(CC.TILES[id]?.monsterKind||''):''}
function pathList(a){const slot=clamp(Number(a.pathSlot??a.railPathSlot)||0,0,MAX_PATHS-1);if(actorMonsterKind(a)==='glider'){a.railPaths=a.railPaths||Array.from({length:MAX_PATHS},()=>[]);while(a.railPaths.length<MAX_PATHS)a.railPaths.push([]);return a.railPaths}a.waypointPaths=a.waypointPaths||Array.from({length:MAX_PATHS},()=>[]);while(a.waypointPaths.length<MAX_PATHS)a.waypointPaths.push([]);return a.waypointPaths}
function activePath(a){const paths=pathList(a),slot=clamp(Number(a.pathSlot??a.railPathSlot)||0,0,MAX_PATHS-1);return Array.isArray(paths[slot])?paths[slot]:[]}
function pathValid(){return []}
function inRange(x,y,w,h){return Number.isInteger(x)&&Number.isInteger(y)&&x>=0&&y>=0&&x<w&&y<h}
function validate(L=current()){const errs=[];if(!L.tiles||L.tiles.length!==L.width*L.height)errs.push('Tile array does not match map size.');if(L.actors.filter(a=>a.type==='chip').length!==1)errs.push('Exactly one Chip start is required.');const ids=new Set();for(const a of L.actors){if(ids.has(a.id))errs.push(`Duplicate actor ID: ${a.id}`);ids.add(a.id);if(!MONSTER_TYPES.has(a.type)||a.type==='chip')continue;if(!Number.isInteger(a.tileId)&&a.type==='monster')errs.push(`Monster ${a.id}: missing linked tile ID.`);if(a.type!=='spider'&&(!Number.isInteger(a.tileId)||!CC.TILES[a.tileId]?.monster))errs.push(`Monster ${a.id}: linked tile must be one of the original monster sprites.`)}for(const p of L.hiddenDirt||[]){if(!inRange(p.x,p.y,L.width,L.height))errs.push(`Hidden dirt is outside the map at ${p.x},${p.y}.`);const i=p.y*L.width+p.x;if(Number.isInteger(p.underTile)&&(p.underTile<0||p.underTile>=CC.TILES.length))errs.push(`Hidden dirt at ${p.x},${p.y} has an invalid underlying tile.`);const ti=Number.isInteger(L.hiddenDirtSettings?.triggerTileId)?L.hiddenDirtSettings.triggerTileId:0x24;if(L.tiles[i]===ti)errs.push(`Hidden dirt at ${p.x},${p.y} cannot also be the red trigger tile.`);if(L.actors.some(a=>a.x===p.x&&a.y===p.y))errs.push(`Hidden dirt at ${p.x},${p.y} cannot overlap an actor.`)}return [...new Set(errs)]}
function mark(label='Unsaved changes'){E.dirty=true;$('dirtyState').textContent='Unsaved';$('dirtyState').className='dirtyState dirty';$('editStatus').textContent=label;$('editStatus').className='status dirty';clearTimeout(E.saveTimer);E.saveTimer=setTimeout(()=>autoSave(),500)}
function autoSave(){try{localStorage.setItem(LS+E.slot,jsonString(current()));E.dirty=false;$('dirtyState').textContent='Saved';$('dirtyState').className='dirtyState saved';$('editStatus').textContent='Autosaved to this browser.';$('editStatus').className='status good'}catch(e){$('editStatus').textContent='Browser autosave unavailable; use Save JSON file.'}}
function snapshotSlot(slot,label){E.history.push({slot,label,data:jsonString(E.levels[slot])});if(E.history.length>60)E.history.shift();E.future.length=0;updateUndo()}
function snapshot(label){snapshotSlot(E.slot,label)}
function undo(){const h=E.history.pop();if(!h)return;E.future.push({slot:E.slot,data:jsonString(current())});E.slot=h.slot??E.slot;E.levels[E.slot]=sanitize(JSON.parse(h.data));E.selectedActorId=null;renderAll();mark(`Undid: ${h.label}`);updateUndo()}
function redo(){const h=E.future.pop();if(!h)return;E.history.push({label:'Redo',data:jsonString(current())});E.levels[E.slot]=sanitize(JSON.parse(h.data));renderAll();mark('Redid last action.');updateUndo()}
function updateUndo(){$('undoBtn').disabled=!E.history.length;$('redoBtn').disabled=!E.future.length}
function setTool(tool){E.tool=tool;E.pathStarted=false;document.querySelectorAll('.tool').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));if(tool==='hiddenDirt')$('editStatus').textContent='Click a cell to mark it as hidden dirt. It will appear when Chip steps on the red trigger (0x24).';if(tool==='path'){const a=current().actors.find(a=>a.id===E.selectedActorId);if(!a||!MONSTER_TYPES.has(a.type))$('editStatus').textContent='Select a monster actor first. Then click any map cells in the order you want.';else $('editStatus').textContent=`Editing path ${(Number(a.pathSlot??a.railPathSlot)||0)+1}. Click up to ${MAX_WAYPOINTS} waypoint cells in any order. No special start, end, or tile is required.`}}
function setActorKind(kind){E.actorKind=kind;document.querySelectorAll('.actor-btn').forEach(b=>b.classList.toggle('activeChoice',b.dataset.kind===kind));}
function uniqueId(type){let i=0;while(current().actors.some(a=>a.id===`${type}-${i}`))i++;return `${type}-${i}`}
function hiddenDirtAt(L,x,y){return (L.hiddenDirt||[]).find(p=>p.x===x&&p.y===y)}
function toggleHiddenDirt(index){
 const L=current(),x=index%L.width,y=Math.floor(index/L.width),existing=hiddenDirtAt(L,x,y);
 if(existing){snapshot('Remove hidden dirt');L.hiddenDirt=L.hiddenDirt.filter(p=>!(p.x===x&&p.y===y));mark('Removed hidden dirt overlay.');renderMap();return}
 snapshot('Place hidden dirt');L.hiddenDirt=L.hiddenDirt||[];L.hiddenDirt.push({x,y,underTile:L.tiles[index]});mark('Placed hidden dirt overlay. It will appear when the red trigger fires.');renderMap();
}
function clearHiddenDirt(){const L=current();if(!(L.hiddenDirt||[]).length)return;snapshot('Clear hidden dirt');L.hiddenDirt=[];mark('Cleared hidden dirt overlays.');renderMap()}
function placeActor(x,y){const L=current();if(E.actorKind==='chip'&&L.actors.some(a=>a.type==='chip')){E.selectedActorId=L.actors.find(a=>a.type==='chip').id;E.placeMode='move';return renderAll()}snapshot('Place '+E.actorKind);let type=E.actorKind,tileId=null;if(type==='monster'){tileId=Number.isInteger(E.selectedTile)&&CC.TILES[E.selectedTile]?.monster?E.selectedTile:0x40}else if(type==='spider')tileId=0x40;else if(type==='spiral')tileId=0x44;else if(type==='glider')tileId=0x50;else if(type==='teeth')tileId=0x54;const monsterKind=Number.isInteger(tileId)?(CC.TILES[tileId]?.monsterKind||''):'';const isGlider=monsterKind==='glider';const cfg=L.monsterSettings||MONSTER_DEFAULTS;const paths=Array.from({length:MAX_PATHS},()=>[]);const a={id:type==='chip'?'chip':uniqueId(type),type,variant:MONSTER_TYPES.has(type)?'red':'default',tileId,x,y,direction:2,speed:type==='spider'?(cfg.spiderMoveMs||800):type==='spiral'?(cfg.spiralMoveMs||600):type==='glider'?(cfg.gliderMoveMs||450):type==='teeth'?(cfg.teethMoveMs||400):(cfg.genericMonsterMoveMs||500),path:[],pathSlot:0,pathMode:type==='spider'?'ai':(isGlider?'rail':'loop'),pathBehavior:(isGlider||type==='monster')?'sequential':'loop',loopFromStart:false,continuousEndBehavior:'return',aiChase:type==='spider'||type==='teeth',visionRange:cfg.defaultVisionTiles||10,focusLoseDistanceTiles:cfg.focusLoseDistanceTiles||10,neverLoseFocus:false,focusMs:cfg.teethFocusMs||5000,buttonBehavior:'freeze',buttonTrigger:type==='monster'?'none':(isGlider?'tan':'none'),waypointPaths:paths,railPaths:isGlider?paths.map(p=>p.slice()):[],railPathSlot:0};L.actors.push(a);E.selectedActorId=a.id;mark(`Placed ${CC.TILES[tileId]?.name||type}. Choose Path 1–6 and click Draw path.`);renderAll()}
function moveSelected(x,y){const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);if(!a)return;$('editStatus').textContent='No actor selected.';snapshot('Move '+a.type);a.x=x;a.y=y;mark(`Moved ${a.type}. Existing waypoints were preserved.`);renderAll()}
function paintAt(index){const L=current(),id=E.tool==='erase'?0:E.selectedTile,hd=hiddenDirtAt(L,index%L.width,Math.floor(index/L.width));if(L.tiles[index]===id&&(!hd||hd.underTile===id))return;if(!E.strokeStarted){snapshot(E.tool==='erase'?'Erase tiles':'Paint tiles');E.strokeStarted=true}L.tiles[index]=id;if(hd)hd.underTile=id;mark(E.tool==='erase'?'Erasing…':'Painting…');renderCell(index)}
function addPathPoint(x,y){const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);if(!a||!MONSTER_TYPES.has(a.type)){setStatus('Select a monster first, then click Draw path.');return}if(!E.pathStarted){snapshot(`Draw path ${((Number(a.pathSlot??a.railPathSlot)||0)+1)}`);E.pathStarted=true}const paths=pathList(a),slot=clamp(Number(a.pathSlot??a.railPathSlot)||0,0,MAX_PATHS-1),p=paths[slot];const limited=a.type==='monster'||actorMonsterKind(a)==='glider';if(limited&&p.length>=MAX_WAYPOINTS){setStatus(`Path ${slot+1} already has ${MAX_WAYPOINTS} waypoints. Clear it to redraw.`);E.pathStarted=false;return}if(p.some(q=>q.x===x&&q.y===y)){setStatus('That cell is already a waypoint. Choose another cell.');return}p.push({x,y});a.path=p.slice();a.pathSlot=slot;a.railPathSlot=slot;mark(`Added waypoint ${p.length} to path ${slot+1}.`);renderMap();renderActorInspector()}
function setStatus(t,kind=''){const el=$('editStatus');el.textContent=t;el.className='status '+kind}
function renderCell(index, actorMap=null, hiddenMap=null, selectedPath=null){const L=current(),x=index%L.width,y=Math.floor(index/L.width);const rx=x-E.viewX,ry=y-E.viewY;if(rx<0||ry<0||rx>=E.viewCols||ry>=E.viewRows)return;const cell=$('mapGrid').children[ry*E.viewCols+rx];if(!cell)return;cell.textContent='';cell.dataset.index=index;cell.dataset.x=x;cell.dataset.y=y;if(!inRange(x,y,L.width,L.height)){cell.hidden=true;return}cell.hidden=false;cell.append(tileEl(L.tiles[index],E.zoom));const hidden=hiddenMap?hiddenMap.get(x+','+y):hiddenDirtAt(L,x,y);if(hidden){const hd=document.createElement('span');hd.className='hidden-dirt-dot';hd.textContent='D';hd.title='Hidden dirt: appears when the red trigger is activated';cell.append(hd)}const actors=actorMap?actorMap.get(x+','+y):L.actors.filter(a=>a.x===x&&a.y===y);for(const a of (actors||[]))renderActorOverlay(cell,a);if(selectedPath)renderPathDots(cell,x,y,selectedPath)}
function renderActorOverlay(cell,a){const idx= a.type==='chip'?0x6C+((a.direction??2)&3):a.type==='spider'?0x40+((a.direction??2)&3):a.type==='spiral'?0x44+((a.direction??2)&3):a.type==='glider'?0x50+((a.direction??2)&3):a.type==='teeth'?0x54+((a.direction??2)&3):a.type==='monster'?((CC.TILES.monsterForTile?.(a.tileId)?.base??0x40)+((a.direction??2)&3)):0x0A;const o=tileEl(idx,E.zoom);o.className+=' actor-overlay'+(a.id===E.selectedActorId?' selected-actor':'');o.dataset.actorId=a.id;o.onclick=e=>{e.stopPropagation();E.selectedActorId=a.id;renderAll();};cell.append(o);const label=document.createElement('span');label.className='actor-label';label.textContent=a.type[0].toUpperCase();cell.append(label)}
function renderPathDots(cell,x,y,path){const i=path.findIndex(p=>p.x===x&&p.y===y);if(i>=0){const d=document.createElement('span');d.className='path-dot'+(i===0?' closed':'');d.textContent=i+1;cell.append(d)}}
function updateViewportMetrics(){const vp=$('mapViewport'),tilePx=32*E.zoom;const cols=Math.max(EDIT_VIEW_TILES,Math.ceil(vp.clientWidth/tilePx)+1);const rows=Math.max(EDIT_VIEW_TILES,Math.ceil(vp.clientHeight/tilePx)+1);if(cols===E.viewCols&&rows===E.viewRows)return false;E.viewCols=cols;E.viewRows=rows;E.viewReady=false;return true}
function renderVisibleCells(){const L=current(),g=$('mapGrid'),actorMap=new Map(),hiddenMap=new Map();const maxX=E.viewX+E.viewCols,maxY=E.viewY+E.viewRows;for(const a of L.actors){if(a.x>=E.viewX&&a.y>=E.viewY&&a.x<maxX&&a.y<maxY){const key=a.x+','+a.y;const list=actorMap.get(key)||[];list.push(a);actorMap.set(key,list)}}for(const p of (L.hiddenDirt||[])){if(p.x>=E.viewX&&p.y>=E.viewY&&p.x<maxX&&p.y<maxY)hiddenMap.set(p.x+','+p.y,p)}const selected=L.actors.find(a=>a.id===E.selectedActorId);const selectedPath=selected&&MONSTER_TYPES.has(selected.type)&&!(selected.type==='spider'&&selected.pathMode!=='loop')?activePath(selected):null;for(let ry=0;ry<E.viewRows;ry++)for(let rx=0;rx<E.viewCols;rx++){const x=E.viewX+rx,y=E.viewY+ry;const cell=g.children[ry*E.viewCols+rx];if(!cell)continue;cell.hidden=!inRange(x,y,L.width,L.height);if(!cell.hidden)renderCell(y*L.width+x,actorMap,hiddenMap,selectedPath);else{cell.textContent='';cell.dataset.index='';cell.dataset.x='';cell.dataset.y='';}}}
function setViewOrigin(x,y){const L=current(),vp=$('mapViewport'),stage=$('mapStage'),g=$('mapGrid'),tilePx=32*E.zoom;updateViewportMetrics();const maxX=Math.max(0,L.width-E.viewCols),maxY=Math.max(0,L.height-E.viewRows);E.viewX=clamp(Math.floor(x),0,maxX);E.viewY=clamp(Math.floor(y),0,maxY);stage.style.width=(L.width*tilePx)+'px';stage.style.height=(L.height*tilePx)+'px';g.style.width=(E.viewCols*tilePx)+'px';g.style.height=(E.viewRows*tilePx)+'px';g.style.gridTemplateColumns=`repeat(${E.viewCols}, ${tilePx}px)`;g.style.gridAutoRows=tilePx+'px';g.style.left=(E.viewX*tilePx)+'px';g.style.top=(E.viewY*tilePx)+'px';ensureCellPool();renderVisibleCells();if(Math.abs(vp.scrollLeft-E.viewX*tilePx)>1)vp.scrollLeft=E.viewX*tilePx;if(Math.abs(vp.scrollTop-E.viewY*tilePx)>1)vp.scrollTop=E.viewY*tilePx}
function syncViewFromScroll(){const L=current(),vp=$('mapViewport'),tilePx=32*E.zoom;const resized=updateViewportMetrics();const maxX=Math.max(0,L.width-E.viewCols),maxY=Math.max(0,L.height-E.viewRows),x=clamp(Math.floor(vp.scrollLeft/tilePx),0,maxX),y=clamp(Math.floor(vp.scrollTop/tilePx),0,maxY);if(!resized&&x===E.viewX&&y===E.viewY&&E.viewReady)return;E.viewX=x;E.viewY=y;const g=$('mapGrid');g.style.width=(E.viewCols*tilePx)+'px';g.style.height=(E.viewRows*tilePx)+'px';g.style.gridTemplateColumns=`repeat(${E.viewCols}, ${tilePx}px)`;g.style.gridAutoRows=tilePx+'px';g.style.left=(x*tilePx)+'px';g.style.top=(y*tilePx)+'px';ensureCellPool();E.viewReady=true;renderVisibleCells();}
function ensureCellPool(){const g=$('mapGrid'),need=E.viewCols*E.viewRows;if(g.children.length===need)return;g.innerHTML='';for(let n=0;n<need;n++){const cell=document.createElement('button');cell.className='map-cell';cell.addEventListener('pointerdown',e=>{e.preventDefault();E.drag=true;handleMapActionFromCell(cell)});cell.addEventListener('pointerenter',()=>{if(E.drag&&(E.tool==='paint'||E.tool==='erase'))handleMapActionFromCell(cell)});g.append(cell)}}
function handleMapActionFromCell(cell){if(cell.hidden)return;const L=current(),x=Number(cell.dataset.x),y=Number(cell.dataset.y);if(!inRange(x,y,L.width,L.height))return;handleMapAction(y*L.width+x)}
function renderMap(){const L=current();updateViewportMetrics();ensureCellPool();$('mapGrid').style.setProperty('--zoom',E.zoom);setViewOrigin(E.viewX,E.viewY);document.body.dataset.tool=E.tool;renderActorList();renderPathInfo();if(E.tool!=='path')setStatus(`Showing ${E.viewCols}×${E.viewRows} visible editing window · top-left: ${E.viewX}, ${E.viewY}`)}
function handleMapAction(index){const L=current(),x=index%L.width,y=Math.floor(index/L.width);if(E.tool==='paint'||E.tool==='erase')paintAt(index);else if(E.tool==='hiddenDirt'){toggleHiddenDirt(index)}else if(E.tool==='actor'){if(E.placeMode==='new')placeActor(x,y);else moveSelected(x,y)}else if(E.tool==='path')addPathPoint(x,y)}
function renderActorList(){const box=$('actorInspector');box.innerHTML='';const L=current();const list=document.createElement('div');list.className='actor-list';L.actors.forEach(a=>{const row=document.createElement('div');row.className='actor-row'+(a.id===E.selectedActorId?' selected':'');const name=document.createElement('button');name.textContent=`${a.type} · ${a.id}`;name.onclick=()=>{E.selectedActorId=a.id;renderAll()};row.append(name);const del=document.createElement('button');del.textContent='×';del.title='Delete actor';del.onclick=()=>{snapshot('Delete actor');L.actors=L.actors.filter(x=>x.id!==a.id);if(E.selectedActorId===a.id)E.selectedActorId=null;mark('Deleted actor.');renderAll()};row.append(del);list.append(row)});box.append(list);renderActorInspector()}
function renderActorInspector(){const box=$('actorInspector');const L=current(),a=L.actors.find(a=>a.id===E.selectedActorId);const title=document.createElement('div');title.className='inspector-title';title.textContent=a?'Selected actor':'No actor selected';box.append(title);if(!a)return;const wrap=document.createElement('div');wrap.className='inspector-grid';
 const mk=actorMonsterKind(a);
 const isPathMonster=(a.type==='monster'||mk==='glider'||a.type==='glider');
 const type=document.createElement('label');type.innerHTML='Type<select id="aType"><option value="chip">Chip</option><option value="spider">Spider</option><option value="spiral">Fireball / Spiral</option><option value="glider">Glider</option><option value="teeth">Teeth (red lips)</option><option value="monster">Custom monster</option><option value="block">Dirt block</option></select></label>';wrap.append(type);
 const typeSel=type.querySelector('select');typeSel.value=a.type;typeSel.onchange=()=>{snapshot('Change actor type');a.type=typeSel.value;a.tileId=a.type==='spider'?0x40:a.type==='spiral'?0x44:a.type==='glider'?0x50:a.type==='teeth'?0x54:a.type==='monster'?(E.selectedTile&&CC.TILES[E.selectedTile]?.monster?E.selectedTile:0x40):a.tileId;const mk=actorMonsterKind(a);a.path=[];a.pathSlot=0;a.railPathSlot=0;a.waypointPaths=Array.from({length:MAX_PATHS},()=>[]);a.railPaths=mk==='glider'?a.waypointPaths.map(x=>x.slice()):[];a.pathMode=a.type==='spider'?'ai':(mk==='glider'?'rail':(['spiral','teeth','monster'].includes(a.type)?'loop':''));a.pathBehavior=(mk==='glider'||a.type==='monster')?'sequential':'loop';a.loopFromStart=false;a.continuousEndBehavior='return';a.buttonTrigger=a.type==='monster'?'none':(mk==='glider'?'tan':'none');a.aiChase=a.type==='spider'||a.type==='teeth'?true:a.aiChase;a.visionRange=a.visionRange||MONSTER_DEFAULTS.defaultVisionTiles;a.focusLoseDistanceTiles=a.focusLoseDistanceTiles||MONSTER_DEFAULTS.focusLoseDistanceTiles;a.neverLoseFocus=!!a.neverLoseFocus;a.focusMs=a.focusMs||MONSTER_DEFAULTS.teethFocusMs;a.buttonBehavior='freeze';mark('Changed actor type.');renderAll()};
 const tileLabel=document.createElement('label');tileLabel.innerHTML='Linked tile<input id="aTile" type="number" min="64" max="99" value="'+(a.tileId??'')+'"></label>';tileLabel.querySelector('input').onchange=e=>{const id=clamp(+e.target.value,64,99);if(!CC.TILES[id]?.monster){setStatus('Choose a real monster tile ID (0x40–0x63, excluding 0x58–0x5B).');e.target.value=a.tileId??64;return}snapshot('Change linked monster tile');const wasGlider=actorMonsterKind(a)==='glider';a.tileId=id;const nowGlider=actorMonsterKind(a)==='glider';if(nowGlider&&!wasGlider){a.waypointPaths=Array.from({length:MAX_PATHS},()=>[]);a.railPaths=a.waypointPaths.map(x=>x.slice());a.pathSlot=0;a.railPathSlot=0;a.path=[];a.pathMode='rail';a.pathBehavior='sequential'}else if(wasGlider&&!nowGlider){a.waypointPaths=(a.railPaths||Array.from({length:MAX_PATHS},()=>[])).map(p=>p.slice());a.railPaths=[];a.pathSlot=0;a.railPathSlot=0;a.path=a.waypointPaths[0]||[];a.pathMode=a.type==='spider'?'ai':'loop'}mark('Changed linked monster tile.');renderAll()};if(['monster','teeth'].includes(a.type))wrap.append(tileLabel);
 const variant=document.createElement('label');variant.innerHTML='Variant<select><option value="red">Red</option><option value="yellow">Yellow</option><option value="default">Default</option></select></label>';variant.querySelector('select').value=a.variant;variant.querySelector('select').onchange=e=>{snapshot('Change actor variant');a.variant=e.target.value;mark('Changed actor variant.');renderAll()};wrap.append(variant);
 const x=document.createElement('label');x.innerHTML='X<input type="number" min="0" max="991" value="'+a.x+'"></label>';x.querySelector('input').onchange=e=>moveActorField(a,'x',e.target.value);wrap.append(x);const y=document.createElement('label');y.innerHTML='Y<input type="number" min="0" max="991" value="'+a.y+'"></label>';y.querySelector('input').onchange=e=>moveActorField(a,'y',e.target.value);wrap.append(y);
 const dir=document.createElement('label');dir.innerHTML='Direction<select>'+directions.map(d=>`<option value="${d[0]}">${d[1]}</option>`).join('')+'</select></label>';dir.querySelector('select').value=a.direction;dir.querySelector('select').onchange=e=>{snapshot('Change actor direction');a.direction=+e.target.value;mark('Changed direction.');renderAll()};wrap.append(dir);
 const speed=document.createElement('label');speed.innerHTML='Move speed (ms/tile)<input type="number" min="100" max="2000" value="'+a.speed+'"><small>Lower = faster</small></label>';speed.querySelector('input').onchange=e=>{snapshot('Change actor speed');a.speed=clamp(+e.target.value,100,2000);mark('Changed speed.');renderAll()};wrap.append(speed);
 if(['teeth','monster'].includes(a.type)){const ai=document.createElement('label');ai.className='rule-check';ai.innerHTML='<input type="checkbox"> Chase Chip when visible';ai.querySelector('input').checked=!!a.aiChase;ai.querySelector('input').onchange=e=>{snapshot('Change monster AI');a.aiChase=e.target.checked;mark('Changed chase behavior.');};wrap.append(ai);const vr=document.createElement('label');vr.innerHTML='Vision / focus range (tiles)<input type="number" min="1" max="32" value="'+(a.visionRange||10)+'">';vr.querySelector('input').onchange=e=>{snapshot('Change vision range');a.visionRange=clamp(+e.target.value,1,32);mark('Changed vision range.');};wrap.append(vr);const fl=document.createElement('label');fl.innerHTML='Focus distance (tiles)<input type="number" min="1" max="32" value="'+(a.focusLoseDistanceTiles||10)+'">';fl.querySelector('input').onchange=e=>{snapshot('Change focus distance');a.focusLoseDistanceTiles=clamp(+e.target.value,1,32);mark('Changed focus distance.');};wrap.append(fl);const nf=document.createElement('label');nf.className='rule-check';nf.innerHTML='<input type="checkbox"> Never lose focus after seeing Chip';nf.querySelector('input').checked=!!a.neverLoseFocus;nf.querySelector('input').onchange=e=>{snapshot('Change focus persistence');a.neverLoseFocus=e.target.checked;mark(e.target.checked?'Monster will keep focus after first sighting.':'Monster can lose focus normally.');renderAll()};wrap.append(nf);if(a.type==='teeth'){const ft=document.createElement('label');ft.innerHTML='Focus duration (ms)<input type="number" min="250" max="60000" value="'+(a.focusMs||5000)+'">';ft.querySelector('input').onchange=e=>{snapshot('Change Teeth focus duration');a.focusMs=clamp(+e.target.value,250,60000);mark('Changed Teeth focus duration.');};wrap.append(ft)}}
  if(isPathMonster&&!(a.type==='spider'&&a.pathMode!=='loop')){
  const bt=document.createElement('label');bt.innerHTML='Button trigger<select><option value="none">None (default)</option><option value="tan">Small tan/brown button (0x27)</option><option value="red">Small red button (0x24)</option><option value="both">Both buttons</option></select><small>Only the selected button(s) control this Glider/custom monster.</small></label>';
  const bts=bt.querySelector('select');bts.value=['tan','red','both'].includes(a.buttonTrigger)?a.buttonTrigger:'none';
  bts.onchange=e=>{snapshot('Change button trigger');a.buttonTrigger=e.target.value;mark(a.buttonTrigger==='none'?'Button trigger disabled for this monster.':`Trigger attached to ${e.target.options[e.target.selectedIndex].text}.`);renderAll()};
  wrap.append(bt);
  if(a.buttonTrigger&&a.buttonTrigger!=='none'){
   const bm=document.createElement('label');bm.innerHTML='When triggered<select><option value="freeze">Freeze / resume at current position</option><option value="station">Continue to nearest station (0x2B)</option></select><small>The chosen button immediately toggles this monster behavior.</small></label>';
   const bs=bm.querySelector('select');bs.value=a.buttonBehavior==='station'?'station':'freeze';
   bs.onchange=e=>{snapshot('Change button action');a.buttonBehavior=e.target.value==='station'?'station':'freeze';mark(a.buttonBehavior==='station'?'The attached button sends this monster to the nearest 0x2B station.':'The attached button freezes/resumes this monster in place.');renderAll()};
   wrap.append(bm);
  }
 }
box.append(wrap);
 if(a.type==='spider'){const pm=document.createElement('label');pm.className='rule-check';pm.innerHTML='<input type="checkbox"> Use authored paths (optional)';const pc=pm.querySelector('input');pc.checked=a.pathMode==='loop';pc.onchange=e=>{snapshot('Change spider path mode');a.pathMode=e.target.checked?'loop':'ai';mark(e.target.checked?'Spider authored paths enabled.':'Spider A* AI restored.');renderAll()};wrap.append(pm)}
 const pathEnabled=MONSTER_TYPES.has(a.type)&&!(a.type==='spider'&&a.pathMode!=='loop');
 if(pathEnabled){
   const paths=pathList(a);a.pathSlot=clamp(Number(a.pathSlot??a.railPathSlot)||0,0,MAX_PATHS-1);a.railPathSlot=a.pathSlot;a.path=paths[a.pathSlot]||[];
   const title=document.createElement('div');title.className='inspector-title';title.textContent=`${mk==='glider' || a.type==='glider'?'Glider':'Custom monster'} waypoint paths`;box.append(title);const quick=document.createElement('div');quick.className='path-note';quick.innerHTML=`<b>Easy waypoint editing:</b> select Path 1–6, click <b>Draw path</b>, then click any map cells in order. Up to <b>${MAX_WAYPOINTS}</b> waypoints per path. No adjacency or special-tile requirements.`;box.append(quick);
   const tabs=document.createElement('div');tabs.className='path-tabs';for(let i=0;i<MAX_PATHS;i++){const b=document.createElement('button');b.textContent=`Path ${i+1}`;b.className=i===a.pathSlot?'activeChoice':'';b.onclick=()=>{a.pathSlot=i;a.railPathSlot=i;a.path=paths[i]||[];mark(`Editing path ${i+1}.`);renderAll()};tabs.append(b)}box.append(tabs);
   const p=activePath(a);const st=document.createElement('div');st.className='path-note';st.textContent=(mk==='glider' || a.type==='glider')?`Path ${a.pathSlot+1}: ${p.length}/${MAX_WAYPOINTS} waypoints. Click Draw path, then click any cells. The path may start or end anywhere. Choose the movement/trigger options below; no special waypoint tile is required.`:(a.type==='monster'?`Path ${a.pathSlot+1}: ${p.length}/${MAX_WAYPOINTS} waypoints. Click Draw path, then click any cells. Waypoints can be anywhere; no special start/end tile is required.`:`Path ${a.pathSlot+1}: ${p.length} waypoints. Click Draw path, then click any cells. Existing monster path behavior is preserved.`);box.append(st);
   if(a.type==='monster'||mk==='glider'){
     const mode=document.createElement('label');mode.className='rule-check';mode.innerHTML='<input type=\"checkbox\"> Continuous loop through paths';const cb=mode.querySelector('input');cb.checked=a.pathBehavior==='loop';
     cb.onchange=e=>{snapshot('Change path behavior');a.pathBehavior=e.target.checked?'loop':'sequential';mark(e.target.checked?'Continuous loop enabled: paths run using the configured end behavior.':'Sequential mode enabled: each path waits for the small brown button.');renderAll()};box.append(mode);
     if(a.pathBehavior==='loop'){
       const end=document.createElement('label');end.innerHTML='At final waypoint<select><option value=\"return\">Return through configured paths toward Path 1</option><option value=\"stay\">Stay at final waypoint</option></select><small>Choose what happens when the final configured path reaches its last waypoint.</small>';
       const es=end.querySelector('select');es.value=a.continuousEndBehavior==='stay'?'stay':'return';
       es.onchange=e=>{snapshot('Change final path behavior');a.continuousEndBehavior=e.target.value==='stay'?'stay':'return';mark(a.continuousEndBehavior==='stay'?'The monster will remain at the final waypoint.':'The monster will return through the configured paths toward Path 1.');renderAll()};box.append(end);
       if(a.continuousEndBehavior!=='stay'){
         const lm=document.createElement('label');lm.className='rule-check';lm.innerHTML='<input type=\"checkbox\"> Loop from the start';const lc=lm.querySelector('input');lc.checked=a.loopFromStart===true;
         lc.onchange=e=>{snapshot('Change loop-from-start');a.loopFromStart=e.target.checked;mark(e.target.checked?'Loop from start enabled: final path restarts at Path 1 from the monster current position.':'Loop from start disabled: final path returns through the configured paths toward Path 1.');renderAll()};box.append(lm);
       }
       const ln=document.createElement('div');ln.className='path-note';ln.textContent=a.continuousEndBehavior==='stay'?'At the final waypoint, the monster stays there until gameplay destroys it.':(a.loopFromStart?'At the final waypoint, Path 1 restarts naturally from the monster current cell; there is no teleport.':'At the final waypoint, the monster returns through the configured paths toward Path 1.');box.append(ln);
     }
     const note=document.createElement('div');note.className='path-note';if(a.pathBehavior==='loop'){note.textContent=a.continuousEndBehavior==='stay'?'Continuous mode: the monster follows the configured paths and then stays at the final waypoint.':'Continuous mode: the monster follows the configured paths; the final-path setting above controls what happens at the end.'}else{note.textContent='Sequential mode: each small brown button activates the next configured path. Use the Small button behavior setting to freeze or route to the nearest 0x2B station.'}box.append(note)
   }

   const edit=document.createElement('button');edit.className='primary';edit.textContent=`Draw path ${a.pathSlot+1}`;edit.onclick=()=>{setTool('path');E.pathSlot=a.pathSlot;E.pathStarted=false;mark(`Drawing path ${a.pathSlot+1}. Click up to ${MAX_WAYPOINTS} waypoints anywhere.`);renderMap();renderActorInspector()};box.append(edit);const finish=document.createElement('button');finish.textContent='Finish waypoint editing';finish.onclick=()=>{E.pathStarted=false;setTool('actor');mark('Waypoint editing finished. Monster settings remain available.');renderAll()};box.append(finish);
   const buttons=document.createElement('div');buttons.className='path-tools';const clear=document.createElement('button');clear.textContent='Clear this path';clear.onclick=()=>{snapshot(`Clear path ${a.pathSlot+1}`);paths[a.pathSlot]=[];a.path=[];mark(`Cleared path ${a.pathSlot+1}.`);renderAll()};const allClear=document.createElement('button');allClear.textContent='Clear all 6 paths';allClear.onclick=()=>{snapshot('Clear all monster paths');for(let i=0;i<paths.length;i++)paths[i]=[];a.path=[];mark('Cleared all monster paths.');renderAll()};buttons.append(clear,allClear);box.append(buttons);
 }
}

function moveActorField(a,key,v){const L=current();snapshot('Move actor');a[key]=clamp(Number(v)||0,0,L[key==='x'?'width':'height']-1);mark('Moved actor. Existing waypoints were preserved.');renderAll()}
function renderPathInfo(){const a=current().actors.find(a=>a.id===E.selectedActorId&&MONSTER_TYPES.has(a.type));if(a&&E.tool==='path'){const p=activePath(a),slot=Number(a.pathSlot??a.railPathSlot)||0;setStatus(`Path ${slot+1}: ${p.length}${(a.type==='monster'||actorMonsterKind(a)==='glider')?'/'+MAX_WAYPOINTS:''} waypoints. Click anywhere to add the next point.`,'')}}
function buildPalette(){const box=$('palette');box.innerHTML='';const q=$('paletteSearch').value.trim().toLowerCase(),group=$('paletteGroup').value;const filtered=CC.TILES.filter(t=>{if(group==='terrain'&&t.id>=64)return false;if(group==='creatures'&&!t.monster)return false;if(group==='items'&&(t.id<100||t.id>=108))return false;if(group==='devices'&&(t.id>=64||[2,0x64,0x65,0x66,0x67,0x68,0x69,0x6A,0x6B,0x6C,0x6D,0x6E,0x6F].includes(t.id)))return false;if(group==='chip'&&(t.id<108))return false;return !q||t.name.toLowerCase().includes(q)||`0x${t.id.toString(16).padStart(2,'0')}`.includes(q)||String(t.id)===q});for(const t of filtered){const b=document.createElement('button');b.className='palette-btn'+(t.id===E.selectedTile?' selected':'');b.title=`0x${t.id.toString(16).padStart(2,'0')} · ${t.name}`;b.onclick=()=>{E.selectedTile=t.id;if(t.monster){E.actorKind='monster';if(E.tool==='actor'){E.placeMode='new';document.querySelectorAll('.actor-btn').forEach(x=>x.classList.toggle('activeChoice',x.dataset.kind==='monster'));renderAll();setStatus(`Monster selected: ${t.name}. Click any map cell to place it, then use Draw / edit path.`);return}}setTool('paint');renderAll()};const p=tileEl(t.id,1.35);p.className+=' preview';b.append(p);const id=document.createElement('span');id.className='id';id.textContent='0x'+t.id.toString(16).padStart(2,'0');const nm=document.createElement('span');nm.className='name';nm.textContent=t.name;b.append(id,nm);box.append(b)}$('paletteCount').textContent=`${filtered.length} tile${filtered.length===1?'':'s'} shown`}
function ruleValue(L,id,key){return L.rules[String(id)]?.[key]??tileMeta(id)[key]??false}
function setRule(id,key,val){const L=current(),base=tileMeta(id),obj=L.rules[String(id)]||{},old=obj[key];let same=String(old??'')===String(val??'');if(same)return;snapshot('Change tile property');const baseVal=base[key];if(val===null||val===undefined||String(val)===String(baseVal))delete obj[key];else obj[key]=val;if(!Object.keys(obj).length)delete L.rules[String(id)];else L.rules[String(id)]=obj;mark('Changed tile property.')}
function renderTileRules(){const id=E.selectedTile,t=tileMeta(id),L=current(),box=$('tileRules');box.innerHTML='';const flags=[['walk','Walkable'],['wall','Wall'],['danger','Dangerous'],['water','Water'],['fire','Fire'],['ice','Ice / slide'],['destructible','Destructible'],['item','Collectible'],['button','Button'],['monster','Monster tile'],['block','Block tile'],['hiddenWall','Hidden wall']];for(const [k,label] of flags){const l=document.createElement('label');l.className='rule-check';const c=document.createElement('input');c.type='checkbox';c.checked=!!ruleValue(L,id,k);c.onchange=()=>{setRule(id,k,c.checked);renderTileRules()};l.append(c,label);box.append(l)}
 const door=document.createElement('select');door.innerHTML='<option value="">Door: none</option><option value="c">Door: cyan</option><option value="r">Door: red</option><option value="g">Door: green</option><option value="y">Door: yellow</option>';door.value=L.rules[String(id)]?.door??t.door??'';door.onchange=()=>{setRule(id,'door',door.value||null);renderTileRules()};box.append(door);
 const force=document.createElement('select');force.innerHTML='<option value="">Force: none</option><option value="0">Force: north</option><option value="1">Force: west</option><option value="2">Force: south</option><option value="3">Force: east</option><option value="-1">Force: random</option>';force.value=L.rules[String(id)]?.force??(t.force==null?'':String(t.force));force.onchange=()=>{setRule(id,'force',force.value===''?null:Number(force.value));renderTileRules()};box.append(force);
 const card=$('selectedTile');card.innerHTML='';const prev=document.createElement('div');prev.className='selected-preview';prev.append(tileEl(id,2));const text=document.createElement('div');text.className='tile-text';text.innerHTML=`<strong>0x${id.toString(16).padStart(2,'0')} · ${t.name}</strong><small>Column ${t.c} · Row ${t.r} · ${t.mask?'sprite with atlas mask':'normal atlas tile'}</small>`;card.append(prev,text);const qa=$('monsterQuickAdd');qa.innerHTML='';if(t.monster){const b=document.createElement('button');b.className='primary';b.textContent=`Place ${t.name} monster`;b.onclick=()=>{E.selectedTile=id;E.actorKind='monster';E.placeMode='new';setTool('actor');document.querySelectorAll('.actor-btn').forEach(x=>x.classList.toggle('activeChoice',x.dataset.kind==='monster'));setStatus(`Selected ${t.name}. Now click a map cell to place it. Then use Draw / edit path.`)};qa.append(b);const n=document.createElement('small');n.textContent=actorMonsterKind({type:'monster',tileId:id})==='glider'?'Glider tiles get a simple 6-path rail editor.':'The exact tileset sprite ID is saved on the actor.';qa.append(n)}}
function renderTop(){const L=current();$('slotSelect').value=String(E.slot);$('titleInput').value=L.title;$('authorInput').value=L.author;$('timeInput').value=L.timeLimit;$('chipsInput').value=L.requiredChips;$('hintInput').value=L.hint;$('widthInput').value=L.width;$('heightInput').value=L.height;$('mapTitle').textContent=L.title||'Map';$('hiddenDirtCount').textContent=(L.hiddenDirt||[]).length+' hidden dirt tile'+((L.hiddenDirt||[]).length===1?'':'s')}
const MONSTER_CONFIG_FIELDS=[['cfgSpider','spiderMoveMs',800],['cfgGlider','gliderMoveMs',450],['cfgSpiral','spiralMoveMs',600],['cfgTeeth','teethMoveMs',400],['cfgFocus','teethFocusMs',5000,'seconds'],['cfgVision','defaultVisionTiles',10],['cfgFocusDistance','focusLoseDistanceTiles',10]];
function syncMonsterConfigUI(){const cfg=current().monsterSettings||{};for(const [id,key,def,kind] of MONSTER_CONFIG_FIELDS){const input=$(id);if(!input)continue;input.value=kind==='seconds'?(Number(cfg[key]??def)/1000):Number(cfg[key]??def)}}
function renderAll(){renderTop();buildPalette();renderMap();renderTileRules();updateUndo();syncMonsterConfigUI()}
function slotOptions(){const s=$('slotSelect');s.innerHTML='';for(let i=0;i<9;i++){const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} · ${E.levels[i].title}`;s.append(o)}s.value=String(E.slot)}
function commitField(id,key,transform=x=>x){const input=$(id);input.onchange=()=>{const L=current(),v=transform(input.value);if(String(L[key])===String(v))return;snapshot('Edit '+key);L[key]=v;mark('Changed '+key+'.');renderTop()};}
function resizeMap(){const L=current(),w=clamp(+$('widthInput').value,5,992),h=clamp(+$('heightInput').value,5,992);if(w===L.width&&h===L.height)return;snapshot('Resize map');const nt=new Array(w*h).fill(0);for(let y=0;y<Math.min(h,L.height);y++)for(let x=0;x<Math.min(w,L.width);x++)nt[y*w+x]=L.tiles[y*L.width+x];L.width=w;L.height=h;L.tiles=nt;L.hiddenDirt=(L.hiddenDirt||[]).filter(p=>p.x<w&&p.y<h);L.actors.forEach(a=>{a.x=clamp(a.x,0,w-1);a.y=clamp(a.y,0,h-1);a.path=(a.path||[]).filter(p=>p.x<w&&p.y<h);if(MONSTER_TYPES.has(a.type)){const paths=pathList(a);for(let i=0;i<paths.length;i++)paths[i]=paths[i].filter(q=>q.x<w&&q.y<h);a.path=paths[a.pathSlot||0]||[];a.railPathSlot=a.pathSlot||0}});mark('Resized map.');renderAll()}
function exportLevel(){const data=jsonString(current()),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');const name=(current().title||'custom-level').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'custom-level';a.href=URL.createObjectURL(blob);a.download=name+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);try{localStorage.setItem(LS+E.slot,data)}catch(e){}E.dirty=false;$('dirtyState').textContent='Saved';$('dirtyState').className='dirtyState saved';setStatus('JSON file saved.', 'good')}
function exportPack(){const pack={schema:'chips-custom-level-pack',version:2,levels:E.levels.map(sanitize),tileset:TILESET};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(pack,null,2)],{type:'application/json'}));a.download='chips-custom-level-pack.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);setStatus('1–9 JSON pack saved.','good')}
async function importFile(file){const d=JSON.parse(await file.text());const items=Array.isArray(d.levels)?d.levels:[d];let loaded=0;for(let i=0;i<items.length&&E.slot+i<9;i++){E.levels[E.slot+i]=sanitize(items[i]);loaded++}E.history=[];E.future=[];E.selectedActorId=null;renderAll();autoSave();setStatus(`Imported ${loaded} level${loaded===1?'':'s'} starting at slot ${E.slot+1}.`,'good')}
function loadSlot(i){if(E.dirty)autoSave();E.slot=i;E.selectedActorId=null;E.history=[];E.future=[];let local=null;try{local=localStorage.getItem(LS+i)}catch(e){}if(local){try{E.levels[i]=sanitize(JSON.parse(local));setStatus(`Loaded browser-saved level ${i+1}.`,'good')}catch(e){}}renderAll()}
function createNew(){snapshot('Create new map');E.levels[E.slot]=makeNew();E.selectedActorId=null;mark('New map created.');renderAll()}
function duplicate(){const next=Math.min(8,E.slot+1);snapshotSlot(next,'Duplicate map');E.levels[next]=sanitize(current());E.levels[next].title=(current().title||'LEVEL')+' COPY';E.slot=next;E.selectedActorId=null;mark(`Duplicated map to slot ${next+1}.`);renderAll()}
function playMap(){const errs=validate();if(errs.length){alert('Fix these editor issues first:\n\n'+errs.join('\n'));return}try{localStorage.setItem('ccPendingLevel',jsonString(current()))}catch(e){alert('Could not hand the map to the game browser storage. Save the JSON instead.');return}window.location.href='index.html'}
function copyJSON(){if(!navigator.clipboard)return setStatus('Clipboard unavailable; use Save JSON file.');navigator.clipboard.writeText(jsonString(current())).then(()=>setStatus('JSON copied to clipboard.','good')).catch(()=>setStatus('Clipboard unavailable; use Save JSON file.'))}
function setZoom(v){const vp=$('mapViewport'),oldTile=32*E.zoom,centerX=E.viewX+Math.floor((vp.clientWidth/oldTile)/2),centerY=E.viewY+Math.floor((vp.clientHeight/oldTile)/2);E.zoom=clamp(Number(v),.75,2.5);$('zoomRange').value=E.zoom;$('zoomLabel').textContent=Math.round(E.zoom*100)+'%';const newTile=32*E.zoom;setViewOrigin(centerX-Math.floor((vp.clientWidth/newTile)/2),centerY-Math.floor((vp.clientHeight/newTile)/2));renderMap()}
function init(){
 setActorKind('spider');slotOptions();renderAll();
 // Global monster defaults used for newly placed/custom actors.
 for(const [id,key,def,kind] of MONSTER_CONFIG_FIELDS){const input=$(id);if(!input)continue;input.onchange=()=>{const before=current().monsterSettings||{};snapshot('Change monster defaults');const v=Number(input.value)||def;const value=kind==='seconds'?clamp(v*1000,250,60000):clamp(v,1,32);if(['spiderMoveMs','gliderMoveMs','spiralMoveMs','teethMoveMs'].includes(key))current().monsterSettings=Object.assign({},before,{[key]:clamp(v,100,2000)});else current().monsterSettings=Object.assign({},before,{[key]:value});window.CC_MONSTER_CONFIG=Object.assign({},window.CC_MONSTER_CONFIG||{},current().monsterSettings);mark('Monster tuning updated.');renderAll()};}
 document.querySelectorAll('.tool').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));
 document.querySelectorAll('.actor-btn').forEach(b=>b.onclick=()=>setActorKind(b.dataset.kind));
 $('placeNewBtn').onclick=()=>{E.placeMode='new';$('placeNewBtn').className='activeChoice';$('moveSelectedBtn').className='';setTool('actor')};
 $('moveSelectedBtn').onclick=()=>{E.placeMode='move';$('placeNewBtn').className='';$('moveSelectedBtn').className='activeChoice';setTool('actor')};
 $('slotSelect').onchange=e=>loadSlot(+e.target.value);
 $('saveBtn').onclick=exportLevel;$('saveDownloadBtn').onclick=exportLevel;$('exportPackBtn').onclick=exportPack;$('copyBtn').onclick=copyJSON;$('playMapBtn').onclick=playMap;$('playGameBtn').onclick=()=>location.href='index.html';
 $('newBtn').onclick=createNew;$('duplicateBtn').onclick=duplicate;$('loadSavedBtn').onclick=()=>loadSlot(E.slot);$('resizeBtn').onclick=resizeMap;$('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('clearHiddenDirtBtn').onclick=clearHiddenDirt;$('importBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=e=>{const f=e.target.files[0];if(f)importFile(f).catch(err=>alert('Could not import JSON.\n\n'+err.message));e.target.value=''};
 commitField('titleInput','title',x=>x.trim()||'CUSTOM LEVEL');commitField('authorInput','author',x=>x.trim());commitField('timeInput','timeLimit',x=>clamp(+x||0,0,999));commitField('chipsInput','requiredChips',x=>Math.max(0,+x||0));commitField('hintInput','hint');
 $('paletteSearch').oninput=buildPalette;$('paletteGroup').onchange=buildPalette;$('zoomRange').oninput=e=>setZoom(e.target.value);$('zoomOut').onclick=()=>setZoom(E.zoom-.1);$('zoomIn').onclick=()=>setZoom(E.zoom+.1);$('mapViewport').addEventListener('scroll',syncViewFromScroll,{passive:true});
 window.addEventListener('pointerup',()=>{E.drag=false;E.strokeStarted=false;E.pathStarted=false});
 window.addEventListener('resize',()=>{E.viewReady=false;renderMap()});
 window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if(e.ctrlKey&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){e.preventDefault();redo()}else if(e.ctrlKey&&e.key.toLowerCase()==='s'){e.preventDefault();exportLevel()}});
 window.addEventListener('beforeunload',()=>{if(E.dirty)autoSave()});
}
const actorBox=$('actorButtons');for(const [type,label,hex] of actorTypes){const b=document.createElement('button');b.className='actor-btn';b.dataset.kind=type;b.innerHTML=`<span class="mini"></span><span>${label}<br><small>${hex}</small></span>`;const mini=b.querySelector('.mini');mini.append(tileEl(+hex,1));actorBox.append(b)}
init();
})();
